### ISSUE TITLE
When is active, the Spotlight shortcut stopped working

### ISSUE THREAD

**Issue by valencar** [aahung/Unshaky#1]
The Cmd + Space shortcut, its not working.

**Comment by azeemmohd** [comment]
@Aahung I have the same issue, here's the log for cmd spacebar:
1529660969.939110	 Key(49)	 Event(11) DISMISSED
1529660969.938952	 Key(49)	 Event(10) DISMISSED
1529660969.936624	 Key(49)	 Event(11)
1529660969.744665	 Key(49)	 Event(10)

**Comment by Aahung** [comment]
@azeemmohd is it for a single "CMD+SPACE" hit or two?

**Comment by azeemmohd** [comment]
Single.

**Comment by Aahung** [comment]
@azeemmohd That's odd, on my Mac when I hit "CMD+SPACE", there are only two lines, and you get 4 lines, which means "keydown + keyup + keydown + keyup"

```
1529661297.247138	 Key(49)	 Event(11)
1529661297.192024	 Key(49)	 Event(10)
```

**Comment by Aahung** [comment]
@azeemmohd can you try this version I just created? It will ignore "space" key for good.

[Unshaky.app.zip](https://github.com/Aahung/Unshaky/files/2127171/Unshaky.app.zip)

**Comment by azeemmohd** [comment]
Perfect. Works like a charm. :)

**Comment by Aahung** [comment]
@azeemmohd Cool I will update the release with this version.

**Comment by Aahung** [comment]
Since I cannot let it reappear on my Mac, I will leave this issue open for now.

**Comment by Aahung** [comment]
@valencar @azeemmohd , what are your OS versions? I wanna if it has something to do with it, like issue #5.

**Comment by aahung** [comment]
I believe this issue is related to #8. I user from reddit reported his log

**Comment by aahung** [comment]
I believe this issue is related to #8. I user from reddit reported his log below

```
First cmd + space (in that order)
1539852170.130042	 Key(55)	 Event(12)
1539852170.129072	 Key(49)	 Event(11) DISMISSED
1539852170.128513	 Key(49)	 Event(10) DISMISSED
1539852170.125920	 Key(49)	 Event(11)
1539852170.010203	 Key(49)	 Event(10)
1539852169.968837	 Key(55)	 Event(12)
```

```
Second
1539852217.898928	 Key(55)	 Event(12)
1539852217.882102	 Key(49)	 Event(11) DISMISSED
1539852217.881431	 Key(49)	 Event(10) DISMISSED
1539852217.878896	 Key(49)	 Event(11)
1539852217.752121	 Key(49)	 Event(10)
1539852217.677462	 Key(55)	 Event(12)
```

```
Third try
1539852269.224504	 Key(49)	 Event(11) DISMISSED
1539852269.223897	 Key(49)	 Event(10) DISMISSED
1539852269.222948	 Key(49)	 Event(11)
1539852269.214551	 Key(55)	 Event(12)
1539852269.070696	 Key(49)	 Event(10)
1539852268.983720	 Key(55)	 Event(12)
```

Notice key 55, which is command key, is registered. While on my Mac (and some other users) the command key is never registered in debug mode. Maybe this is the reason why I can never make this issue appear on my Mac. I will look into it later.

**Comment by aahung** [comment]
I think I was wrong, 55 indeed showed up on my Mac :-(

**Comment by aahung** [comment]
More report from that user: option+space does not induce two consecutive spaces. So command key is the reason.

```
And here's option+space:
1539853598.433661	 Key(49)	 Event(11)
1539853598.418123	 Key(58)	 Event(12)
1539853598.325666	 Key(49)	 Event(10)
1539853598.272385	 Key(58)	 Event(12)
```

**Comment by xunga** [comment]
I worked around by setting the ms of delay for only the spacebar to 0. So far so good...

**Comment by ghost711** [comment]
I just submitted pull request #18  for this issue. As you said @aahung , this is related to #8.
Key presses with CMD pressed results in double events in rapid succession, but it's possible to check event flags and ignore the duplicate if needed.

**Comment by aahung** [comment]
@ghost711 you found it out. That's awesome! I never could reproduce this problem on my Mac.

**Comment by daothanhduy305** [comment]
@aahung Somehow the build I have built for myself including all the latest commits from the dev branch still have the issue with CMD + space.

**Comment by aahung** [comment]
@daothanhduy305 Currently `dev` branch is a failed experiment 😞. The PR #19 might resolve the `CMD+SPACE` issue, but create other issues. So a fully working workaround will come in the (foreseeable) future.

**Comment by ghost711** [comment]
Damn, that's too bad.  It's still working perfect for my machine. Guess there must be more variables than I thought at first.  Oh well.  Good luck!

**Comment by aahung** [comment]
As @ghost711 said, it might be ok now to try out #19 (just with a very small issue I think: possibly `CMD+SPACE` double press). I think I will soon come up with something adopting #19 method and in the meanwhile does not break the original functionality.

**Comment by aahung** [comment]
Guys, please try this version of [Unshaky (v0.3.0)](
https://files.nestederror.cf/file/-public-/Unshaky_v0.3.0.app.zip) and turn on the option below:

<img width="432" alt="screen shot 2018-11-19 at 4 45 43 pm" src="https://user-images.githubusercontent.com/3804518/48744169-fb0c6b00-ec1a-11e8-92bd-6efd73c1028c.png">

**Comment by daothanhduy305** [comment]
Thanks, I'll try it later. Mine is currently at an AASP for a keyboard repair (Not only duplicating the spacebar but also it doesn't work for some pressing position).

**Comment by aahung** [comment]
@daothanhduy305 that is great!
