### ISSUE TITLE
Czech & Slovak translation

### ISSUE THREAD

**Issue by username0x0a** [aahung/Unshaky#100]
**Language**
Czech & Slovak

**Can you help with the translation?**
Yes, sure! 👍

**Comment by aahung** [comment]
Hi @michalzelinka  thanks for your interest. A branch named "lang/cs" has been created and you can see 5 string files in "cs.lproj", same goes for "lang/sk"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR for Czech or Slovak.

Thanks!

**Comment by aahung** [comment]
@username0x0a thank you so much for your contributions to make Unshaky accessible to more people. And sorry I seemed to at the wrong person above...
