### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by norbert05** [aahung/Unshaky#106]
**Language**
Hungarian

**Can you help with the translation?**
(Yes/No)

**Comment by aahung** [comment]
Hi @norbert05  thanks for your interest. A branch named "lang/hu" has been created and you can see 5 string files in "hu.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!
