### ISSUE TITLE
b key still repeats

### ISSUE THREAD

**Issue by mitchwyle** [aahung/Unshaky#11]
I have tried setting the ms delay to all values I could think of and the B key still repeats 1/3 times I press B.  Is the program a software "debounce" system that will prevent double-keys within a time?  If so, what does  the msec delay mean?  TIA

**Comment by aahung** [comment]
You are right, Unshaky prevents any press within such time frame. if it is 40 ms, two key presses have to be at least 40ms away. 
If it does not work for you, post your debug window and mark which key presses are not expected.

**Comment by aahung** [comment]
(close due to inactivity)
