### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by blazeblazeblaze** [aahung/Unshaky#111]
**Language**
Polish

**Can you help with the translation?**
Yes

**Comment by youshy** [comment]
If there's a need for extra help - you can count on me @blazeblazeblaze

**Comment by aahung** [comment]
Sorry for the delay.

Hi @blazeblazeblaze @youshy thanks for your interest. A branch named "lang/pl" has been created and you can see 5 string files in "pl.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!

**Comment by blazeblazeblaze** [comment]
Thanks mate, I'll get the branch ready today. Happy to merge it along with @youshy changes.

**Comment by blazeblazeblaze** [comment]
@aahung @youshy I reckon it's done (5 files). Feel free to review and merge if you're happy with that 🎉

**Comment by aahung** [comment]
Awesome!!!

**Comment by aahung** [comment]
Thanks for making this happen!
