### ISSUE TITLE
Key event isn't propogated until released (occasionally)

### ISSUE THREAD

**Issue by Falmarri** [aahung/Unshaky#117]
**Describe the bug**
When a key is configured with a timeout, it delays the key down event until key up

**To Reproduce**
1. Set up a key delay (space bar in my case)
2. Press the space bar key, wait momentarily and then release
3. You'll notice that the space doesn't show up until the key is released

It's hard to time exactly right, but I notice that I end up `typinga lotl iket his` no matter what the configured debounce timeout is

**Expected behavior**
If it's not within the double press window, don't delay the key down event

**Comment by aahung** [comment]
@Falmarri can you also post the debug window content?

**Comment by Falmarri** [comment]
So I'm having trouble replicating it, but I still get the situation where spaces are typed after the next letter. It might just be the awfulness of the mac keyboard though rather than this tool

**Comment by aahung** [comment]
Either is possible. Please keep me updated in case you reproduce it. I need to investigate the log to find the issue, thanks!

**Comment by aahung** [comment]
close due to inactivity.
