### ISSUE TITLE
macOS Catalina Beta - Accessibility Settings Checkbox not working (and the workaround)

### ISSUE THREAD

**Issue by brad07x** [aahung/Unshaky#118]
When configuring Unshaky on macOS Catalina Beta [10.15 Beta (19A526h)], the checkbox to allow accessibility access for Unshaky in System Preferences -> Security & Privacy -> Accessibility ('Allow the apps below to control your computer') cannot be marked to grant accessibility control permissions.

1. Open Unshaky.app for the first time and acknowledge the message about granting accessibility permissions.
2. The System Preference pane for Security & Privacy -> Accessibility opens.
3. Trying to tick the checkbox for Unshaky.app to grant permissions has no effect (checkbox does not 'tick') and permissions are not granted for Unshaky.
4. Re-opening Unshaky results in the notification about permissions, confirming that permissions were not granted. Unshaky cannot operate as a result.

Workaround:
1. In the System Preference pane for Security & Privacy -> Accessibility, select Unshaky.app from the list and click the "-" button to remove the app from the list.
2. Click the "+" button to browse for a new app to add to the list.
3. Navigate to the install location for Unshaky (/Applications in my case) and select Unshaky to be added back to the list of apps.
4. After selecting Unshaky from the browse window and adding it back to the list, the checkbox for granting permissions is properly 'ticked'.
5. Unshaky works as expected after following these workaround steps (this resolved the issue for me).

It seems like the issue happened when Unshaky populated itself in the System Preference pane for Security & Privacy -> Accessibility apps list. Manually removing and adding the app back worked without issues.

Not sure if this is an issue with Unshaky or macOS Catalina Beta, but since the other checkboxes  for other apps worked without issue I thought it was worth filing a bug.

Unshaky is working great to address the key doubling issues I'm having on my MacBook Pro 15,1 (2018). I've already taken advantage of the keyboard service program and the issues still persist for certain keys, so Unshaky is a godsend.

**Comment by aahung** [comment]
@brad07x just felt bad about myself since I removed Catalina from my disk last week 😢. Thanks for providing this workaround, since Catalina is the beta software, I will re-visit this bug the week before Catalina is officially released to everyone (September).

**Comment by DavidNgoDev** [comment]
Thanks. Worked like a charm.

**Comment by aahung** [comment]
Close this issue, it served its purpose well.
