### ISSUE TITLE
THANK YOU SO MUCH

### ISSUE THREAD

**Issue by kilazi** [aahung/Unshaky#119]
this saves me so much damn trouble -- I dont have an option to give in my macbook for a repairs for 2 weeks because I'm in a constant travel

hey make this app paid & on the appstore, I'm gonna buy it even though i have this open source version (and I believe many of us will!)

anyway, great thanks to you and the contributors, this is a life-saving piece of software >:)

**Comment by aahung** [comment]
@kilazi glad it helps. Unshaky uses accessibility API which is not allowed on the App Store (has to be sandbox App to be there. Unshaky is still notarized by Apple to scan malware though).

Unshaky is a fairly simple application, and I think it does not reach the line I think it deserves charging people money :D 

If you want to support this project monetarily 😀, there is a small "donate" button on the GitHub page.

**People like you keep this project alive!**
