### ISSUE TITLE
Make available to change all configuration values at once

### ISSUE THREAD

**Issue by Ilkhom-S** [aahung/Unshaky#12]
Hello,
Changing all key delay is little bit annoying. Can you add option to change all keys delay at once

**Comment by aahung** [comment]
@Ilhom-S Ummm.. how many key delays do you need to set? In normal scenarios, there seems to be only one or a several keys with issues.

**Comment by billmag** [comment]
I've successfully used this program to help with double presses caused by essential tremor (medical condition involving hand shaking), which would be made easier with an option like this.

**Comment by Ilhom-S** [comment]
My keyboard seems have issues on all char keys

**Comment by aahung** [comment]
@Ilkhom-S @billmag can you try version [v0.2.4](
https://github.com/aahung/Unshaky/releases/tag/v0.2.4)?

**Comment by Ilkhom-S** [comment]
Let me check, thanks

**Comment by aahung** [comment]
<img width="368" alt="screen shot 2018-09-25 at 10 52 44 am" src="https://user-images.githubusercontent.com/3804518/46032729-42f69200-c0b1-11e8-9adc-00b11a920eb1.png">

**Comment by Ilkhom-S** [comment]
Thanks, it's working now.

**Comment by aahung** [comment]
glad it helps

**Comment by Ilkhom-S** [comment]
Did you use default value(40) if values was 0 ?

**Comment by aahung** [comment]
Nope, 40 is just a suggested value. Without setting anything, it is 0 by default.

**Comment by Ilkhom-S** [comment]
ohhh, that's why I see this picture on my program. 
![image](https://user-images.githubusercontent.com/446667/46033009-88997600-c116-11e8-87cd-e15e637318bb.png)
I think you should make note on main page. Because I thought, after launching app filters by default. I see dismiss counter and think that app already filtering.

**Comment by aahung** [comment]
That's odd. If a key is 0, Unshaky will do nothing to it.

**Comment by Ilkhom-S** [comment]
Yes, now I get you. But on main page there is no info to configure delays to app work properly. There is only note that delay is configurable. That's why I launched app and thought that it's already filtering. 

Anyway appreciate for you fast response. And thanks for your app.

**Comment by aahung** [comment]
oh thx, didn't expect that 😃
