### ISSUE TITLE
Keyboard layout not saved

### ISSUE THREAD

**Issue by sachazufferey** [aahung/Unshaky#120]
**Describe the bug**
When I change the keyboard layout to "QWERTZ" (French Switzerland in my case) and I close the configuration windows, when I open it again, the configuration is back to "US"

**To Reproduce**
1. Go to Configuration
2. Change layout to QWERTZ
3. Close the windows
4. Open Configuration again

**Expected behavior**
QWERTZ must be savd

**Desktop (please complete the following information):**
 - macOS version: 10.14.6

**Comment by aahung** [comment]
thanks for reporting the issue
