### ISSUE TITLE
Configuration window multi-editing feature.

### ISSUE THREAD

**Issue by hazarek** [aahung/Unshaky#122]
There is no need SET ALL button. just set the selected keys is enough.
Multiple selection with COMMAND and SHIFT keys,  something like this;

![multi-edit](https://user-images.githubusercontent.com/36481442/64282154-76969900-cf5d-11e9-8fd7-49b7491a9a2e.gif)

or

press COMMAND+A to select all keys then press SET button

**Comment by aahung** [comment]
Thanks for the suggestion, I think it is a nice addition.

The current design decision is to make setting a universal delays explicit, with the combination of "set all" and "enabled" checkboxes. 
Holding Command/Shift to multi-select or shortcut like Command A are great idea, and they can do more things than the current interfaces. But they are implicit, and requires users to try before knowing the function is there.

**Comment by Zandor300** [comment]
Maybe you can do that the button says "Set all" if no rows are selected but as soon as `selectedRows.count > 0`, you change it to "Set selected". Obviously with matching behavior.

*(I know that the table view doesn't work that way, but it was easier to explain.)*

**Comment by hazar-e** [comment]
what is difference beetween "0 delay" and "disabled" checkbox? also there is need a "disable all" checkbox, One by one make it very hard to mark.
