### ISSUE TITLE
Greek localization

### ISSUE THREAD

**Issue by kwstasna** [aahung/Unshaky#127]
**Language**: Greek

**Can you help with the translation?**
Yes

Hello and thanks for this awesome work.
I would like to help you with the greek translation of the strings. 🤘

**Comment by aahung** [comment]
@kwstasna First sorry for the terrible delay here.

Thanks for your interest. A branch named "lang/el" has been created and you can see 5 string files in "el.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!
