### ISSUE TITLE
Add ability to import/export configs

### ISSUE THREAD

**Issue by stackdumper** [aahung/Unshaky#13]
Thanks for your work. I live in country where I have no ability to fix my MBP keyboard with Apple Keyboard Service program, and Unshaky is the only thing that allows me to use my MBP normally.

It would be great to have an ability to import/export keys delay configuration. It took some time for me to configure delays for every broken key I have.

**Comment by aahung** [comment]
Hi there, I am a little confused why you need import/export feature, do you have multiple MacBooks or you will lose the configuration regularly?

**Comment by stackdumper** [comment]
I don't. However, in the future, I might want to do a factory reset and give my MBP to my friend. It would be nice if I could provide him with the ready Unshaky configuration for this specific MBP :)

So I don't think this is a high-priority feature.

**Comment by aahung** [comment]
That makes sense. Will add this in the future

**Comment by aahung** [comment]
![image 5](https://user-images.githubusercontent.com/3804518/47589676-b8f35080-d91e-11e8-953a-f3698edb2ed6.png)
Will be in the next release

**Comment by aahung** [comment]
![screen shot 2018-10-26 at 12 57 34 pm](https://user-images.githubusercontent.com/3804518/47589703-cad4f380-d91e-11e8-8d11-ff8fb2758b94.png)
Will be in the next release
