### ISSUE TITLE
Add hide menubar icon option please

### ISSUE THREAD

**Issue by a-x-** [aahung/Unshaky#130]
**feature request**

Icon is useless and takes a place, 

<img width="592" alt="Screenshot 2019-10-12 at 15 54 14" src="https://user-images.githubusercontent.com/6201068/66701771-c6107780-ed08-11e9-9d4f-48e7881ce705.png">

**Comment by aahung** [comment]
See [How to hide Unshaky from status bar](https://github.com/aahung/Unshaky/wiki/How-to-hide-Unshaky-from-status-bar)

**Comment by aahung** [comment]
Duplicate #24

**Comment by a-x-** [comment]
Wiki pages on github are often empty. So I’m not sure, but I don’t see wiki unless readme refers it. 

Can you add link to the recipe for further curious people?

**Comment by aahung** [comment]
@a-x- totally make sense. Thanks for pointing that out.

**Comment by ushuz** [comment]
@aahung Maybe add a link on app's configuration page to the wiki?
