### ISSUE TITLE
Karabiner Conflict

### ISSUE THREAD

**Issue by korgoth** [aahung/Unshaky#131]
**Describe the bug**
Unshaky seems to be in conflict with Karabiner (i guess since they both capture/modify user input).  When Karabiner is running unshaky's debug window is empty, and it starts capturing events immediately after i stop karabiner

**To Reproduce**
explained above

**Expected behavior**
be able to still capture events after Karabiner (in sort of a chain reaction fashion)

**Desktop:**
 - macOS version: Catalina 10.15 (also observed on all Mojave versions)

**Comment by aahung** [comment]
do you have "ignore external keyboard" on?

**Comment by korgoth** [comment]
Yes i do?

**Comment by aahung** [comment]
Does turning that off make it work? I guess Karabiner modifies the keyboard type of internal keyboard in some way

**Comment by korgoth** [comment]
I just tried ti, and i am getting some input in the unshaky debug window now! Thanks for that - would have never thought of it!

**Comment by aahung** [comment]
The info you gave helped with that guess. Now I know it is for sure. I will look into Karabiner's source code (luckily it is open sourced) and figure out what are changes they possibly make.

**Comment by MWYang** [comment]
Would it be possible to enable Unshaky on a per-keyboard basis? So Unshaky could be enabled for Karabiner's "external" keyboard but disabled for other external keyboards.

**Comment by johanhugg** [comment]
Any luck with this? Would love to use unshaky

**Comment by aahung** [comment]
> Would it be possible to enable Unshaky on a per-keyboard basis? So Unshaky could be enabled for Karabiner's "external" keyboard but disabled for other external keyboards.

It is a good idea, but the amount of work required by it: UI+code makes does not justify the values as far as I can feel. It does not seem many people have this need. Would love to see someone could take on this though.

> Any luck with this? Would love to use unshaky

Luck with what specifically?
