### ISSUE TITLE
Hi ! If there is a demand for Hebrew translation. i would love to help

### ISSUE THREAD

**Issue by aschlon4** [aahung/Unshaky#132]
**Language**
English to Hebrew

**Can you help with the translation?**
(Yes/No)

Yes

**Comment by aahung** [comment]
Sorry recent issues have been heavily delayed. Are you still interested in translation?

**Comment by aschlon4** [comment]
Hi ! Yep, still interested

**Comment by aahung** [comment]
First thanks for your interest. A branch named "lang/he" has been created and you can see 5 string files in "he.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

**Comment by aahung** [comment]
close due to inactivity
