### ISSUE TITLE
translate to persian ( farsi )

### ISSUE THREAD

**Issue by Sia7ash** [aahung/Unshaky#139]
**Language**

**Can you help with the translation?**
hi mate
yes
i can translate from english to persian so the persian language people can use this as well
thank for your amazing app

**Comment by aahung** [comment]
Sorry recent issues have been heavily delayed. Are you still interested in translation?

**Comment by Sia7ash** [comment]
Hi mate , of course , I would love to help and translate this app.how may i help?

**Comment by aahung** [comment]
Thanks for your interest. A branch named "lang/fa-2" has been created and you can see 5 string files in "fa.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

someone tried to translate Persian but seems unfinished. I am not sure whether #98 will help.

**Comment by Sia7ash** [comment]
ok sure , i will translate them asap,thanks for letting me do this

**Comment by aahung** [comment]
@Sia7ash can you directly change the file? Github does convert comments to file changes. Also, /* ... */ are comments and they don't need translation.

**Comment by Sia7ash** [comment]
@aahung sure , ok , sorry

**Comment by Sia7ash** [comment]
@aahung what branches should i translate?fa or fa_2 ?!?

**Comment by aahung** [comment]
@Sia7ash no worry. I did not know how Github works either, it is not very intuitive.

**Comment by aahung** [comment]
`fa-2` please.

**Comment by Sia7ash** [comment]
Hi mate
Marry Christmas , wish you happy new year
translating to persian is Done
see if anything need change
thanks.

**Comment by aahung** [comment]
Great! really appreciate the effort! Where did you put files?

**Comment by Sia7ash** [comment]
I edited them and saved them but apparently there is no edit!
i'm so confused !

**Comment by Sia7ash** [comment]
i found the problem! 
You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork Sia7ash/Unshaky, so you can send a pull request.

**Comment by aahung** [comment]
got it. It seems that you created pull requests from your `Counter.strings` branch to your `lang/fa-2` branch. Can you create pull requests that targeting `aahung/Unshaky`'s `lang/fa-2` branch?

This might be useful: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by Sia7ash** [comment]
done
hope it is OK now
