### ISSUE TITLE
Enable only for built-in keyboard

### ISSUE THREAD

**Issue by anfomin** [aahung/Unshaky#14]
I switch to external keyboard at the office. Can Unshaky determine external keyboard and disable key blocking when one is connected?

**Comment by aahung** [comment]
It is a good point 👍

**Comment by aahung** [comment]
![screen shot 2018-10-28 at 2 06 12 am](https://user-images.githubusercontent.com/3804518/47614022-1dfd9200-da56-11e8-9282-e158199ca7b1.png)

**Comment by anfomin** [comment]
Thank you! I'll test this feature.
