### ISSUE TITLE
Default delay

### ISSUE THREAD

**Issue by Coder-256** [aahung/Unshaky#143]
**Is your feature request related to a problem? Please describe.**
I was very confused about why the app was not working at first, then I realized that the default minimum delay is 0.

**Describe the solution you'd like**
There should be a reasonable default for all keys, maybe 40ms.

**Describe alternatives you've considered**
Maybe this isn't necessary at all, or maybe there could be a different default.

**Additional context**
N/A

**Comment by aahung** [comment]
That is a great point!

**Comment by aahung** [comment]
I rethink it a bit. usually a user only needs to configure one or two faulty keys. It does not make sense to enable by default for all keys.
