### ISSUE TITLE
Detect Common Key Repetitions

### ISSUE THREAD

**Issue by InnovativeInventor** [aahung/Unshaky#145]
**Is your feature request related to a problem? Please describe.**
I have a very aggressive (read: high) delay for my mac's `i` key, which always double or triple presses. This works excellently most of the time, however, when I type in `init`, the second `i` can crap out.

**Describe the solution you'd like**
I would like to be able to specify word pairs that can be safely ignored.

**Describe alternatives you've considered**
An alternative I've tried is reducing the delay for my mac's `i` key, but that gives way too many false positives.

**Additional context**
I'd be willing to help out on this. I can also find/generate common key combinations that we can recommend to people. Not sure if other people are experiencing the same difficulty.

**Comment by InnovativeInventor** [comment]
Just as a note - the example on the README could be fixed by adding in `ap` as a common letter pairing. We could even allow the user to add arbitrary length strings as a common pairing/combination of keypresses (in the example in the README, they would add `apple`).

**Comment by aahung** [comment]
it is a great idea but I don't know how to implement this. How Unshaky works is to prevent ongoing keypress from registration. When user types `apple`, we don't know whether he wants to type `apartment` or `apple` without they actually types the more characters. 😢

**Comment by InnovativeInventor** [comment]
Yes, that’s true. However, we could reduce the delay if the user types in a common letter pairing. For example, if the user types in `ap`, we can reduce or halve the input delay since `app` or `apple` are likely as opposed to when the user types `[[:space:]]p`, since `[[:space:]]pp` is a very unlikely pairing. All we would need is to do is keep track of the previous key presses.

**Comment by aahung** [comment]
@InnovativeInventor that is a very interesting and innovative solution. Unfortunately, currently I don't really have the time to develop a prototype to test its effectiveness... 😞

**Comment by Xenthio** [comment]
you could use a simple counter to find the keys most pressed twice really quickly. have a var for each key and find each keys count that is greater than a configurable value.

**Comment by InnovativeInventor** [comment]
Yeah @Xenthio. This is really just a *somewhat smart* outlier detector.

**Comment by aahung** [comment]
close now because with current resources I won't be able to pull this off
