### ISSUE TITLE
Arabic Localization 

### ISSUE THREAD

**Issue by yosif111** [aahung/Unshaky#148]
**Language**
Arabic

**Can you help with the translation?**
(Yes/No)
Yes!

**Comment by aahung** [comment]
Hi @yosif111 thanks for your interest. A branch named "lang/ar" has been created and you can see 5 string files in "ar.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!

**Comment by aahung** [comment]
close due to inactivity
