### ISSUE TITLE
Not working on OS Mojave (10.14.1 beta)

### ISSUE THREAD

**Issue by nabtron** [aahung/Unshaky#15]
It's not working on OS Mojave with latest update (10.14.1 beta)

**Comment by aahung** [comment]
Thanks for reporting this. Is there anything in debug window? (When you press the keys you configured delays for)

**Comment by nabtron** [comment]
Ok I'm sorry it's working now. I had to change the delay to 500ms to make it work
Also, can you add a way to check the version of app?
And one more issue is that once we configure it, and close configure window, then try to reopen it, it doesn't (on mojave).

**Comment by aahung** [comment]
As for displaying version, I plan to add auto-update at the same time. Coming to "releases" and manually downloading/installing seems to be a hassle.

**Comment by nabtron** [comment]
yes it does work under normal delay, but maybe my keyboard needs longer delay to avoid duplication.

**Comment by aahung** [comment]
Oh great
