### ISSUE TITLE
Danish translations

### ISSUE THREAD

**Issue by ramlev** [aahung/Unshaky#152]
**Language**

Danish

**Can you help with the translation?**

yes

**Comment by aahung** [comment]
Hi @ramlev thanks for your interest. A branch named "lang/da" has been created and you can see 5 string files in "da.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!

**Comment by aahung** [comment]
close due to inactivity
