### ISSUE TITLE
Add an option to disable statistics in menu

### ISSUE THREAD

**Issue by amphioxusiv** [aahung/Unshaky#154]
Hi. Firstly thank you for that app. I want to little thing from you. Seeing shaky presses statistics makes me sad. Therefore I don't want to see the counter. I would be very happy if you could add such an option to the settings. Thank you

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Remove counter

**Describe alternatives you've considered**
None
**Additional context**

**Comment by aahung** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/3804518/102000331-56df3c00-3c9b-11eb-8f73-6aade6ba49a8.png">
