### ISSUE TITLE
kind of worked but then stopped

### ISSUE THREAD

**Issue by amitudeshi** [aahung/Unshaky#158]
my letter b doubles, but there is a delay. i can type the word bebcause, and you can see how it impacts me. I have gotten some improvement with varying time delays. I kept increasing it, but it is currently at 1,200 and still went wrong as demonstrated at the top of this. Do you know what could be happening?

**Comment by aahung** [comment]
weid. 1,200 is apparently too large a delay. Doesn't 40-80 range work for you?

**Comment by amitudeshi** [comment]
I switched it back to 80 now. it doesn’t catch everything, but I have 215 shaky’s now, so it’s probably getting the majority.
