### ISSUE TITLE
ignore any unconfigured key to reduce typing latency

### ISSUE THREAD

**Issue by bsphere** [aahung/Unshaky#159]
is it possible to ignore any key that is not marked in Unshaky, or set to 0ms, to reduce a tiny bit of noticeable latency while typing which is added by Unshaky?

**Comment by aahung** [comment]
Unshaky only has a very minimal operation on keys with 0 delay. Do you have the debug window open? debug window will significantly slow down the Unshaky.

**Comment by bsphere** [comment]
the typing is a little bit less responsive with Unshaky running, it probably won't be an issue for most people but i can definetly notice it.

I have a Macbook Pro 13" 2018 with a double spacing issue. i actually unchecked all other keys except for the spacebar in Unshaky's configuration. I don't have the debug window open...

**Comment by aahung** [comment]
The [`CGEventMask`](https://developer.apple.com/documentation/coregraphics/cgeventtype?language=objc) does not seem to support masking individual keys... so sorry unfortunately I don't think there is a way to do so...
