### ISSUE TITLE
Whole system hangs when Accessibility permission is removed while Unshaky is running

### ISSUE THREAD

**Issue by angelsanz** [aahung/Unshaky#160]
**Describe the bug**
The whole system mostly hangs when Accessibility permission is removed while Unshaky is running.

**To Reproduce**
1. Launch Unshaky.
2. Go to Security & Privacy settings, and disable Accessibility permission for Unshaky.
3. Attempt to switch windows (Cmd+Tab), show Mission Control, launch Spotlight, etc.
4. None of that works for a while. The system does not freeze completely (e.g. music keeps playing in the background) but it takes a few seconds to respond, then mostly hangs again.

**Expected behavior**
It should not hang at all. Perhaps it should warn that it won't work without Accessibility permission, although it should not need such a strong permission, see #157.

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.4.

**Comment by hazarek** [comment]
* macOS Catalina 10.15.5
I tried and the computer froze for 10 seconds.

**Comment by aahung** [comment]
Input monitoring cannot replace the Accessibility permission for now, see [comment](https://github.com/aahung/Unshaky/issues/157#issuecomment-669409152) for detail.

**Comment by angelsanz** [comment]
Understood. Not sure that tackles the computer hanging issue though.

**Comment by aahung** [comment]
Is it a valid issue? Why would you want to remove the accessibility permission while using Unshaky?

**Comment by angelsanz** [comment]
To test if it actually needs it when you aren't sure about that.

Admittedly, it's not part of the main use case, but the effect it causes is oversized and unexpected.

**Comment by hazarek** [comment]
> Is it a valid issue? Why would you want to remove the accessibility permission while using Unshaky?

Ad Hominem
![440px-Graham's_Hierarchy_of_Disagreement svg](https://user-images.githubusercontent.com/36481442/89610551-772d6300-d883-11ea-9407-0966dbd96b24.png)
