### ISSUE TITLE
Unshaky doesn't work with Bitwarden

### ISSUE THREAD

**Issue by a-ershov** [aahung/Unshaky#164]
**Describe the bug**
Sometimes unshaky stop working and debug windows is empty.

**To Reproduce**
Not every time it stops working, but until you close Bitwarden debug windows is empty and unskaky not working.

**Desktop (please complete the following information):**
 - macOS version: 10.15.6

**Additional context**
Unshaky doesn't stop working every time and every day. But after the close of Bitwarden, everything is fine. This is very strange. Bitwarden is open source password management https://bitwarden.com/

**Comment by aahung** [comment]
Do you have the option ignore external keyboard on? It is likely Bitwarden changes the keyboard types.

**Comment by aahung** [comment]
Close due to inactivity
