### ISSUE TITLE
Unshaky compatibility for Macos 11 / Bug Sur

### ISSUE THREAD

**Issue by vstoppe** [aahung/Unshaky#168]
While planning an upgrade to Macos 11 I am searching for information about the compatibility of Unshaky to Big Sur. any experiences yet?
Without Unshaky I get mad using my MBP 16"!

**Comment by aahung** [comment]
I just upgraded to big sur two days ago. Unshaky still works as expected. (I did not go through the installation process, so I cannot say the same about installing)

**Comment by flash76** [comment]
Unshaky does not work for me. I tried using 0.6.0, to no avail, and tried building 0.6.1, but was experiencing errors with certificates while building.

**Comment by aahung** [comment]
> Unshaky does not work for me. I tried using 0.6.0, to no avail, and tried building 0.6.1, but was experiencing errors with certificates while building.

Did you check out this issue? https://github.com/aahung/Unshaky/issues/166
