### ISSUE TITLE
Address delayed repeating key error (ex. flintn)

### ISSUE THREAD

**Issue by richardxu100** [aahung/Unshaky#170]
**Is your feature request related to a problem? Please describe.**
Unshaky has been a life-saver for me, but there is still a rather annoying bug that comes up somewhat often, which is a key repeating, right after another key is pressed. For example, I have a bad _n_ key, so sometimes when I type a word with an _n_ in the middle, the _n_ will not be repeated right afterwards, but will repeat right after the key following _n_. An example is the word _flint_ being mispelled to _flintn_.

**Describe the solution you'd like**
I wonder if a contributor could add an option to handle this kind of error. I think the implemented solution will look similar to the solution for stopping key repeated characters, but would maybe implement some sort of window, so that errant key presses are discarded in a wider window than just the following key.

**Describe alternatives you've considered**
I've just started typing slower, to not run into as many issues.

**Comment by richardxu100** [comment]
I didn't notice that there is an aggressive mode. This mode may be addressing the exact issue I'm facing, so if so, please feel free to close this issue out!

**Comment by aahung** [comment]
Great!
