### ISSUE TITLE
macOS Big Sur compatible icon update.

### ISSUE THREAD

**Issue by hazarek** [aahung/Unshaky#171]
**Is your feature request related to a problem? Please describe.**

icon sizes and shapes are not compatible with big sur
<img width="204" alt="Ekran Resmi 2020-11-30 19 42 39" src="https://user-images.githubusercontent.com/36481442/100646960-d42bb800-334f-11eb-9369-c3dbb696fd38.png">
![Ekran Resmi 2020-11-30 21 06 58](https://user-images.githubusercontent.com/36481442/100647080-0c32fb00-3350-11eb-9818-69455bcb7c42.png)

**Describe the solution you'd like**

My new logo design attempt. Butterfly icon for Butterfly  mechanism
,<img width="313" alt="Ekran Resmi 2020-11-30 20 58 14" src="https://user-images.githubusercontent.com/36481442/100647315-616f0c80-3350-11eb-956f-39d49c8bf886.png">
![unshaky_big_sur](https://user-images.githubusercontent.com/36481442/100647273-54521d80-3350-11eb-85be-443c1d5969cd.png)

https://gist.github.com/hazarek/e7b809e5ebb9078ea7b083aaccc7ffc3
https://gist.github.com/hazarek/5ed3a2bdc0fc3f7b3bd7dfc262a8a5ed

**Describe alternatives you've considered**

If you do not like my design, the old logo should be modified.

**Comment by aahung** [comment]
The icons are amazing! I cannot think of a reason why not. Thanks!

**Comment by aahung** [comment]
Just two comments:
- do we have copyright issue with the butterfly image? 
- The stroke alignment seems a bit off

**Comment by hazarek** [comment]
no shape is  cc license. i can update design tonight.

**Comment by aahung** [comment]
> no shape is cc license. i can update design tonight.

Cool. Thank you, appreciated that!

**Comment by hazarek** [comment]
## ICNS screenshot
<img width="852" alt="Ekran Resmi 2020-12-03 21 14 51" src="https://user-images.githubusercontent.com/36481442/101070875-f66e4180-35ac-11eb-85e8-8f24064d1879.png">

## All files
https://yadi.sk/d/M3APOHjat9R6Fw?w=1
https://gist.github.com/hazarek/b6436b7c9c07bf5ae56553c33da12e9e

## About menu bar icon
I couldn't find a template for the BigSur menu icon. I could not find it in the addresses below. I need a template for menu icon.
https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras
https://developer.apple.com/design/resources/#macos-apps

**Comment by aahung** [comment]
Thank you so much, this looks great! I still prefer the original colors. I did a bit tweaking. Changed the color to ones picked from [here](https://color.adobe.com/My%20Color%20Theme-color-theme-16281439), and increase the gap between the butterfly and stroke (because small gap looks odd when putting on task bar, the gap will disappear). 

Here is the new version, I wonder if you are ok with it.

![status v3 3x](https://user-images.githubusercontent.com/3804518/101612377-6c184a00-39bf-11eb-9fdf-c3e86a601cee.png)
![logo v3](https://user-images.githubusercontent.com/3804518/101612380-6d497700-39bf-11eb-94ca-93f7289fd170.png)

* BTW, I am also a affinitydesigner user 🤝

**Comment by hazarek** [comment]
I can't build the branch you provided, I'm not a macos developer, I don't know xcode and swift. I know Python.
your change has been better. Thank you.

**Comment by hazarek** [comment]
Right curve is not smooth.
<img width="84" alt="Ekran Resmi 2020-12-09 17 49 55" src="https://user-images.githubusercontent.com/36481442/101645122-0ff90880-3a47-11eb-96ee-3240bb9ec513.png">

**Comment by aahung** [comment]
Fixed!

**Comment by aahung** [comment]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/3804518/101684204-e6c28300-3a1a-11eb-9741-48dbfe36d61a.png">

release soon

**Comment by aahung** [comment]
@hazarek Thank you again for providing this new icon!

**Comment by hazarek** [comment]
@aahung  Can you make menu icon little smaller. The icon is bigger than the Big Sur system icons. the margin should be slightly more.

**Comment by aahung** [comment]
Will update 👍

**Comment by aahung** [comment]
Right it is aligned: the spotlight icon and unshaky icon both have 1 pixel exceeding the black line.

It looks like macOS big sur itself does not enforce a constant icon height. spotlight is 1px higher than battery, and control center is taller and not centered. I think we are good now

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/3804518/102000456-82aef180-3c9c-11eb-9dbb-6c055b7640c5.png">

**Comment by hazarek** [comment]
thanks excellent
