### ISSUE TITLE
Unshaky does not work on Macbook Air 2018 Catalina 10.15.7

### ISSUE THREAD

**Issue by kimmpsss** [aahung/Unshaky#176]
I have been trying to get unshaky to work for me on my macbook air 2018 model with catalina 10.15.7 but nothing seems to work. I have tried deleting and redownloading it, making sure that all settings are right under system preferences but it still does not register any keys or dismisses any. What can I do? I am still unable to find a way to add unshaky to input monitoring and the app has not asked for access to it.

**Comment by dataloudercom** [comment]
Did you try the workaround in #166?

**Comment by aahung** [comment]
Did you try the workaround in #166?

**Comment by aahung** [comment]
Close due to duplicate. Move to #172
