### ISSUE TITLE
Doesn't work at all on Big Sur 11.2

### ISSUE THREAD

**Issue by Lodimup** [aahung/Unshaky#177]
**Describe the bug**
Doesn't work at all on Big Sur 11.2

**To Reproduce**

1. Install Unshaky
2. Give permissions in

- Developer tools
- Input Monitoring
- Accessibility

_Debug window returns nothing._

**Expected behavior**
_Debug window returns key presses._

**Desktop** 
MacbookPro13 2018 Big Sur 11.2
Internal Keyboard
External Keyboard G613

**Additional notes**
Works perfectly on my Catalina Desktop

**Comment by aahung** [comment]
Did you configure the key delays?

**Comment by Lodimup** [comment]
> Did you configure the key delays?

Oh my god. I did not. Thank you! Sorry to bother you.
