### ISSUE TITLE
doesn't work with iterm2

### ISSUE THREAD

**Issue by rxqy** [aahung/Unshaky#181]
**Describe the bug**
Unshaky works well with everything (e.g., chrome, default terminal) else but not with iterm2
I still  get shaky inputs  in my iterm2

**To Reproduce**
Open unshaky and  type sth in iterm2

**Expected behavior**
works with iterm2

**Screenshots**
I added a gif with iterm2(left)  and   default terminal(right) here. I only set the delay of space to be 9999ms.  So  I should not be able to type multiple spaces at the same time. 

https://user-images.githubusercontent.com/34204646/130395735-8628047b-f9a4-4e9b-b2c8-5078be645faf.mov

**Desktop (please complete the following information):**
 - macOS version: 10.15.7
 - iterm2 version:  Build 3.4.8

**Additional context**
They are both running zsh, so it might be a problem with iterm2 itself?

**Comment by aahung** [comment]
It is possible iterm2 listens to keyboard events directly and Unshaky won't be able to intercept them. Can you check whether iterm has accessibility permission and whether turning off it resolves it.

**Comment by rxqy** [comment]
Many thanks! I'll look into it if I have time
