### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by jbarbero** [aahung/Unshaky#186]
I just want to say thank you for this app. It is a freaking lifesaver!

My only suggestion is, can you please add a paypal donation link or something? I would happily contribute. This app is saving me from a potentially $500-$700 repair and I just want to show my appreciation. You guys are the best.

Thank you!

**Comment by aahung** [comment]
Good to hear it make your life easier! 

I do have a donation link in README but I don't encourage to do so anymore because I am no longer actively maintaining it.
