### ISSUE TITLE
Unshaky for Mac Boot Camp

### ISSUE THREAD

**Issue by ShevaDavid** [aahung/Unshaky#189]
Unshaky saved my live on my Mac. I installed Windows on my mac using Boot Camp and have hard times with this keyboard.
Is it possible to have Unshaky for Windows?

**Comment by aahung** [comment]
Glad to hear Unshaky has been helpful on your Mac. Currently, there are no plans to develop Unshaky for Windows, but you might find KeyDebouncer at https://github.com/mackncheesiest/KeyDebouncer useful as an alternative. I haven't tried it myself, but it could be a good solution for your needs.
