### ISSUE TITLE
Not working on 14.1.1 (23B81) Sonoma

### ISSUE THREAD

**Issue by KruinKop** [aahung/Unshaky#194]
**Describe the bug**
Seems like the app stopped working after the Sonoma update some time ago. I already tried reinstalling and revoking/granting all the permissions but still no luck. 
Counter stays at 0.

**Desktop (please complete the following information):**
 - macOS version: 14.1.1 (23B81) Sonoma
 - 2018 MBP

**Additional context**
I'd realy appreciate any update for the app as it's the only reason my MBP is workable

**Comment by aahung** [comment]
@KruinKop I have 14.1.1 installed and it works for me. Is anything showing up in your debug window?

**Comment by KruinKop** [comment]
Just checked it and it's showing a blank screen.. I will try to reinstall and check permissions again

**Comment by KruinKop** [comment]
well that did the trick, I also reinstalled karabiners which is some keybinding software. looks like they may have interfered with eachother.. Anyway thanks for the fast response and many thanks for this great program!
