### ISSUE TITLE
About & Settings tab (launch on startup)

### ISSUE THREAD

**Issue by nabtron** [aahung/Unshaky#20]
Can you have an about tab to the app? Which will show the current version & any other such info?

Also, can you add settings to it which will allow it to automatically run on startup?

**Comment by aahung** [comment]
Right now, the version is directly shown in the menu. What kind of “other info” do you mean?

I tried to add launch on startup option but encountered some difficulties (since it is non sandbox app). I might be able to figure it out in the future or any advices are welcome.

**Comment by CristianMoisei** [comment]
This app is a great idea, thanks for making it. An option to hide the menu bar app would be nice if that is possible.

**Comment by aahung** [comment]
>This app is a great idea, thanks for making it. An option to hide the menu bar app would be nice if that is possible.

@CristianMoisei nice you said that. See #24 for hiding menu bar item.

**Comment by CristianMoisei** [comment]
@aahung oh, I didn't know you could do that. Thanks for the tip.

**Comment by aahung** [comment]
I don't want to investigate too much time on the option to "auto launch on startup" since the user only has to configure once.
