### ISSUE TITLE
Application quits.

### ISSUE THREAD

**Issue by mahmai** [aahung/Unshaky#22]
**Describe the bug**
The app quits when set button is clicked with empty value.

**To Reproduce**
1. Go to 'configure'
2. Click on 'set' with out giving value
4. App quits!

**Expected behavior**
Message like 'please provide value in millisecs '.
**Desktop (please complete the following information):**
 - macOS version: 10.14.1

**Comment by aahung** [comment]
Thanks for reporting this bug! Fix should be coming soon.

**Comment by mahmai** [comment]
By the way giving  a fraction value (i.e.) in any of the individual keys  or in the set all field also crashes the app. I  need to set fraction value because letter `e` is giving me a hard time. I set the value  for letter `e` to 1 millisec but it still sends double keystrokes  and I can see that it is registered on the debug window too. Help me out please.

**Comment by aahung** [comment]
@mahmai You should try larger values instead of smaller ones. You can gradually increase from 40ms until it works.

**Comment by mahmai** [comment]
What? 👁 I think that value was for the delay right?

**Comment by aahung** [comment]
yep. if it is 0.1ms, the Unshaky will not prevent any key presses after 0.1ms, which is practically 100% the case

**Comment by mahmai** [comment]
Oh man! My bad` I totally misunderstood the basic concept. Sorry.

**Comment by mahmai** [comment]
Yeah, Adding instructions of how it works in the `README` could help dummies like me :). what I though was that the milliseconds are values in millisecs that determine the delay in which the second keystroke is sent and I thought that by making that value as little as possible I could avoid the key code from being sent. I never thought that it was the threshold value for `Unshaky` to track for the key strokes. Anyhow I think It's working fine. Thank you!

**Comment by aahung** [comment]
Just added an illustration image in README. I think now it is clearer! Thx for your suggestion dude.
