### ISSUE TITLE
is it possible to make the menu icon bar removable?

### ISSUE THREAD

**Issue by nimrodbens** [aahung/Unshaky#24]
just for us guys that like to keep the menu bar clean from third party apps. thank you, great app! it works great for me.

edit: sorry, *menu bar icon

**Comment by aahung** [comment]
It might be worth to look into. Turning it into a preference pane could be a way to go. Not sure how difficult to do it.

**Comment by nimrodbens** [comment]
if I'm not mistaken adding this:
    `statusItem.behavior = .removalAllowed`
on line 44 of `AppDelegate` should do the trick. im not 100% sure.

**Comment by aahung** [comment]
Oh thx, I will try it tmr. 

If it works, I maybe need to add a shortcut to toggle it.

**Comment by nimrodbens** [comment]
thank you! by adding this line i think it allows you to drag the icon out of the menu bar (and it reappears if you "open" the app again - it is already open in the background). about a toggle im not sure. thanks.

**Comment by aahung** [comment]
That's neat. I think I will include it in the next release if it is simple as that! Thanks!

**Comment by nimrodbens** [comment]
happy to :) hope it will.

**Comment by aahung** [comment]
@nimrodbens I tried and I can remove it from the status bar. However, I could not get it back... I checked activity monitor it is there but the item is not showing up after I open Unshaky again.

**Comment by aahung** [comment]
I think I found the solution. I did a few experiments and found `applicationDidBecomeActive` is only invoked if "you "open" the app again if it is already open in the background" (quote you XD), so I can manually set status bar item visible.

**Comment by nimrodbens** [comment]
i was just in the middle of replying back to you and suggesting something like `willEnterForegroundNotification` like in iOS :) I'm happy you found it. im an iOS developer for 3 years now and never programmed to macOS. happy you got it to work :)

**Comment by aahung** [comment]
XD. Guess just need to test a little bit before pushing it to everyone. A big thanks for giving me the hint. 

Here you go: [v0.3.2](http://unshaky.nestederror.com/Unshaky_v0.3.2.app.zip)

**Comment by nimrodbens** [comment]
thanks a lot :) happy to.

**Comment by aahung** [comment]
[v0.3.2](https://github.com/aahung/Unshaky/releases/tag/v0.3.2) released on GitHub.

**Comment by aahung** [comment]
See [How to hide Unshaky from status bar](https://github.com/aahung/Unshaky/wiki/How-to-hide-Unshaky-from-status-bar)
