### ISSUE TITLE
Does not work on lock screen

### ISSUE THREAD

**Issue by tisba** [aahung/Unshaky#25]
I have an issue with one key and Unshaky works okayish most of the time. But it does not seem to work at all on the lock screen (e.g. after waking from sleep, or after explicit locking)

**To Reproduce**
1. active the lock screen
1. type in my password containing the "problematic key"
1. key press is registered twice.

**Expected behavior**
I expect the key not to be repeated.

- macOS version: 10.14.2 (18C54)
- Unshaky 0.3.1

**Additional context**
I have configured the key with a `40ms` delay. It does not seem to matter if I type the password in normal speed or extra slowly. It does not seem to be caught.

**Comment by aahung** [comment]
Thanks for reporting this, right now Unshaky uses `kCGSessionEventTap` which 

>  is placed at the point where HID system and remote control events enter a login session

I might try to switch to `kCGHIDEventTap`, which according to [Apple Documentation](https://developer.apple.com/documentation/coregraphics/cgeventtaplocation?language=objc)

> is placed at the point where HID system events enter the window server.

**Comment by aahung** [comment]
Tried, unfortunately, it does not work.

**Comment by tisba** [comment]
I have no idea if this helps or not, but I think https://github.com/tekezo/Karabiner-Elements does hook into the system in a way that also covers the lock screen.

In any case, thank you for this tool. It helps a lot to bridge the time before I can have my keyboard replaced by 🍎 

💕

**Comment by aahung** [comment]
Thanks @tisba, I will take a look when I get some time. If it is trivial changes I should be able to implement it soon.

**Comment by SmilinBrian** [comment]
The type of event tap Unshaky uses is subject to Secure Event Input which Apple turns on for *all* password fields. That is, Secure Event Input is enabled for the password field on the lock screen as well as being enabled in password fields in web forms. The intent is to secure your passwords against any possible malicious key event tapping software. Getting around this would require a serious change to how Unshaky works.

**Comment by aahung** [comment]
I just experimented myself and it is true. Never found that out, thanks for the info! @SmilinBrian

**Comment by aahung** [comment]
close this because I am not capable of doing it.

**Comment by sharmaeklavya2** [comment]
I think we should mention this issue in the readme or the wiki. It took me a long time to realize that unshaky's behavior is different for password and non-password fields.
