### ISSUE TITLE
Butterfly Keyboard Issue Survey

### ISSUE THREAD

**Issue by aahung** [aahung/Unshaky#26]
@apophenist had an idea to do an open survey with Unshaky to find out how severe this issue is at the current stage. We have been thinking collecting statistics such as "fail rate" of problematic keys. 

If user chooses to opt-in the survey, Unshaky will record some statistics in the background and send out provided user's consent. 

It is working in progress and I open this issue for discussion.

**Comment by alsuhr-c** [comment]
Hi, 

I have this problem pretty bad onmy keyboard. I noticed most-commonly-usd keys started failing first: first backspace, then 'e', 'n', and 'o', now space,'r', 't'... I type fast and am pretty hard on the keyboard (coming from a 3rd gen Macbook Pro).

**Comment by tisba** [comment]
I like the idea in general and with an explicit opt-in even more.

One potential problem though is the amount of false-positives. My observation is that quite some time, for specific phrases and words I trigger Unsaky causing typos. Most of the time it does the right thing, but I'd guess ~20% of the time Unshaky intervenes it's a false positive (and yes, I'v tried several timing values already).

**Comment by aahung** [comment]
False positive is a risk, and only users know how often it happens, qualitatively :-(.

**Comment by tisba** [comment]
I'm not a statistician, but I'm sure there are ways to apply methods to ensure the statistical significance.

**Comment by dfdy** [comment]
I could be okay with a 100% opt-in process that doesn't collect any personal information at all. Maybe just the laptop year/model and a unique random identifier.

**Comment by andhikamaheva** [comment]
> I could be okay with a 100% opt-in process that doesn't collect any personal information at all. Maybe just the laptop year/model and a unique random identifier.

+1

**Comment by arekm** [comment]
Related for those interested in if this is a common problem.

There is https://discussions.apple.com/thread/8536157 thread about keys repeating (title "MacBook Pro 15" (2018) Keyboard "t" key repeating issue?") with "I have this question, too (55192)" button.

So 55192 people found this thread and clicked it confirming the problem.

**Comment by aahung** [comment]
omg I didn't expect that many of people have this issue...

**Comment by aahung** [comment]
Provided people have enough attention on this issue after the recent WSJ article, and Apple issues an apology statement right after it. I don't think a survey that only sample the "faulty keyboards" can be very meaningful. Thanks for the discussion here!
