### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by JeremyKeusters** [aahung/Unshaky#27]
Just a quick thank you note for developing this software! I've been having these issues with my keyboard from time to time with different keys. They usually last for a few days or weeks and then disappear again for some time. This also means that it doesn't really makes sense to pass by the Apple Store..

A few days ago, I had this issue again with the o key of my keyboard which decides to put a double 'o' in 1 out of 6 times. I stumbled upon this software today and it really relieves most of the pain! Thank you so much for releasing and maintaining this! Keep up the good work!

**Comment by aahung** [comment]
Appreciate that! Hope it continues to work for you.

**Comment by melissamcewen** [comment]
Also thank you!! A lifesaver for people like me with dyspraxia!
