### ISSUE TITLE
Several of my keys still double type

### ISSUE THREAD

**Issue by alsuhr-c** [aahung/Unshaky#28]
Hi,

Thanks so much for creating this app! It has definintely helped a lot on my keyboard (and given all they typos here, that's saying somtehing about how bad my keyboard has gotten). Already since installing it two days ago (and using a secondary keyboard most of the time) I have had >50 double key presses rejected. 

However, I am still having some keys double type (I'm leaving in typos in this message so you can see the rate at which it happens). Most cmomonley with the "n" key,although 'o' is also common. 

Sometims, maybe at an equal rate of double typing, I get the keyboard ignoring pressse, and delayed keypresses (you can see them in this message as well!). I am not sure if this is something Unshaky can fix (although it could probably cause keys not to be pressed if the delay is too high?). Maybe I should just get the keyboard replaced...

I'm a pretty fast typer, so I tried to set everything pretty low (right now, 'n', my most finicky key, is set to 15ms). Any ideas?

Thanks!
Alane

**Comment by aahung** [comment]
Hi, glad to know some of double types are prevented. 
15 ms delay is too short for me when I experimented with different delays, so you are really a fast typer! 

Based on my observation, the abnormal bounce usually happens 10-30 ms after the key press, so setting the delays greater than 30 ms is ideal. If you type faster than that, and need to have shorter delays (e.g., 15 ms), Unshaky won't be able to differentiate a normal press and an abnormal bounce :-(. 

It is odd that you have delayed types. I have two guesses:
- you type really faster maybe your fingers cannot keep sync with your mind so you actually type out of order 😆
- there are some other application running in background also hooking the keyboard events. I try to keep Unshaky efficient and response to response to keyboard events very quickly. If some other applications do some relative heavy computation on every keyboard event, it might cause some delays. It is just my guess.

**Comment by alsuhr-c** [comment]
Hm, maybe I should try resetting everything to 30ms again. 

I do type very fast but don't have delay issues on my external keyboards! :) 

And hope I don't have any kind of keylogger... hahaha. 

Thanks for the advice!

**Comment by aahung** [comment]
Wait... I forgot to do the math. `15 ms` means you can press the same key around 66 times per second, maybe the delay is indeed too short...

Then the delay may be due to the short key travel, it responses so fast. 

Hope your problems can be resolved soon!
