### ISSUE TITLE
Setting custom value

### ISSUE THREAD

**Issue by Petahh** [Aahung/Unshaky#3]
Hello, first of all thanks a lot for developing this, its amazing. However I still get sometimes double press. Could you please possibly implement option to change time from 40ms to something little more aggressive? Thanks!

**Comment by Petahh** [comment]
I have changed your code slightly, i have added in `&& (keyCode == 45 || keyCode == 11)` condition for keys which are troubling me and increased time from `0.04` to `0.10` so its more effective. If anyone wants below is snippet of `ShakyPressPreventer.m` and below it are all keyCodes of Mac keyboard.

![image](https://user-images.githubusercontent.com/7292374/42169148-3451a068-7e13-11e8-8e3f-19eac1ec49db.png)

![image](https://user-images.githubusercontent.com/7292374/42169101-1cfd3c1a-7e13-11e8-8cf7-a6892ae49656.png)

**Comment by Aahung** [comment]
I think only preventing the trouble key is better, as you did in your case. Glad it helps.

**Comment by Aahung** [comment]
0.10 second is kind of long for me, since I sometimes type faster (for example “sunny”) than that. Just customize it as you want.

I end up getting my keyboard replaced under Apple’s new service program.

**Comment by Petahh** [comment]
@Aahung I'm afraid Apple service program doesn't have solution to this problem and that they will just replace keyboard with same faulty components. For me it's company laptop so whatever fix my problem without having to wait for weeks is good enough. Please, Let me know once your laptop is back from service or rather if you will face the keyboard problems again after repair.

**Comment by Aahung** [comment]
It’s already back and it fixes it, for now.

The keyboard itself is not faulty, just fragile (to dust). So replacing it can resolve the issue for some time, maybe months, years.

**Comment by Aahung** [comment]
FYI, [v0.2.0](https://github.com/Aahung/Unshaky/releases/tag/v0.2.0) can set delays for individual keys.

**Comment by Petahh** [comment]
Thanks a million @Aahung, works like charm!
