### ISSUE TITLE
Randomly starts blocking dashboard key

### ISSUE THREAD

**Issue by cperezabo** [aahung/Unshaky#30]
Unshaky randomly starts blocking the dashboard key (at least the only key I could detect by now).

Don't know hot to reproduce it, it happens randomly but never stops. If you close the app and re open it works as expected.

<img width="429" alt="screen shot 2019-02-14 at 21 22 00" src="https://user-images.githubusercontent.com/3604722/52859970-f3bb0780-310c-11e9-9ce1-9b474140965f.png">

macOS version: 10.14.3

**Comment by cperezabo** [comment]
It's not random. I've fond it starts happening after opening the debuger.

how to reproduce?
- open unshaky
- open debug window
- press launchpad key
- now press it again. DEAD. unshaky starts blocking it.

**Comment by aahung** [comment]
Thanks for reporting it. It is an issue I think I can fix right away.

**Comment by aahung** [comment]
kind of busy these days. Should fixed soon, still some changes to be done.

**Comment by aahung** [comment]
@cperezabo hi can you try whether 0.3.3 works? thanks

[Unshaky_v0.3.3.zip](https://github.com/aahung/Unshaky/files/2883580/Unshaky_v0.3.3.zip)

**Comment by cperezabo** [comment]
Yes it works!
