### ISSUE TITLE
Running Unshaky for a long time can disable some keys 

### ISSUE THREAD

**Issue by dmitrygz** [aahung/Unshaky#31]
**Describe the bug**
When Unshaky runs for more than (usually)  12 hours, it is possible that (in my case) keys "2" and "3" will stop working completely. I don't really know why those two keys exactly and I am not sure that this only happens after 12 hours, but it's the average running time after which I usually find myself restarting the app because of the issue. Restarting the application completely solves the issue, which I believe means that the problem lies within Unshaky.

**To Reproduce**
1. Start Unshaky.
2. Type a lot for a long time.
3. Issue can possibly happen here.

**Expected behavior**
I did not expect keys "2" and "3" to stop working 🤷‍♀️🤷‍♀️🤷‍♀️

**Desktop (please complete the following information):**
 - macOS version: 10.14.2

**Additional context**
I am a programmer, I type at a decent speed (~110 WPM), and I usually type a lot of text per day, so it might be an issue of keypresses and not the application running time.

**Comment by aahung** [comment]
Can you check the delays (ms) for key "2" and "3"?
Also, do you switch users or put your laptop to sleep during that time. Some users report switching users (or logout) might cause some issues, but I have not yet find the cause.

**Comment by aahung** [comment]
Also, next time if "2" or "3" do not work, can you open the debug window of Unshaky, press those keys and post the content here? It might help with diagnosis

**Comment by aahung** [comment]
Re-open if necessary.
