### ISSUE TITLE
Add an option to select time limit for repeated stroke

### ISSUE THREAD

**Issue by Zajozor** [Aahung/Unshaky#4]
I am using this app for a few days now, but the problem is that it saves me from double "b" hits only sometimes. It seems like the 40ms is not enough to cover the second stroke.

It often happens to me, that the second "b" only appears after the next letter,
eg. instead of "macbook" you get "macbobok".

A bigger timeout could fix this issue.

thanks.

**Comment by Aahung** [comment]
Expect this feature to be implemented in a few days.

**Comment by Aahung** [comment]
Try [v0.2.0](https://github.com/Aahung/Unshaky/releases/tag/v0.2.0)

**Comment by Zajozor** [comment]
works wonderfully, youre a best ! thanks.
