### ISSUE TITLE
Ignore external keyboard ignores internal keyboard on 2018 MacBook Pro 15

### ISSUE THREAD

**Issue by chmac** [aahung/Unshaky#40]
**Describe the bug**
I've set all keys to 40ms. I'm typing in a text editor with the debug window open. Only modifiers produce output in the debug window. Shift, caps lock, fn, control, option, command. The rest of the keys produce no output, and no settings applied to them seem to have any effect. (I've tried setting keys to 500ms, no effect).

**Desktop (please complete the following information):**
 - macOS version: 10.14.2
- Unshaky 0.4.3

**Additional context**
I haven't tried restarting the computer since I installed Unshaky. I have restarted Unshaky multiple times, no change. Happy to follow debugging steps if anyone can suggest them.

**Comment by MacDragon** [comment]
I think knowing which computer would be relavant, is it a 2018? I tried it and had similar results, nothing seemed to happen.

**Comment by chmac** [comment]
Yeah, it’s a 15” MacBook Pro late 2018. Did you ever find a solution? :-)

**Comment by aahung** [comment]
@chmac you mentioned you tried all options right, even unchecking all options? What is your keyboard layout? In the meanwhile I will create a modified version to show more debug info.

**Comment by chmac** [comment]
@aahung It seems to be an intermittent problem. Sometimes when I resume the mac from sleep it works (like right now) and sometimes I see nothing in debug. It seems like the Unshaky app doesn't resume from sleep in some situations. Happy to try out a build with more debugging options in those situations if I can observe the same conditions again.

**Comment by aahung** [comment]
@chmac Here is the modified version that displays all the information Unshaky can capture, it might reveal something. When it is still running but it does not work, check the debug window.

[Unshaky_v0.4.4_debug.zip](https://github.com/aahung/Unshaky/files/2968860/Unshaky_v0.4.4_debug.zip)

**Comment by chmac** [comment]
@aahung I've finally got unshaky again in a "broken" state. It's not capturing any keystrokes right now. I'm running the debug version you posted above. My debug window is blank. I only opened the debug window once it was already in this state. I've tried setting all keys to a 40ms delay, but no change. Restarting unshaky has solved the issue. Now I see all keystrokes logged.

Anything else I could try when it's in the "broken" state? Can I safely leave the debug window open for a very long time or will it have a hard time after a few weeks of continuous use?

**Comment by aahung** [comment]
@chmac thanks for it. I think there might be something wrong with the event tapping. I don't know why this could happen. Someone else reported similar issue after battery dies, and it could be related.

Two possible causes but I don't know how to verify either easily...:

- some rare system event reset the event tap so Unshaky cannot receive any events
- some other software has conflict with Unshaky

I think implementing a recovery mechanism is a feasible workaround.

**Comment by chmac** [comment]
It seems to be related to suspend / resume. That's just an anecdotal impression, so it might not be accurate. Maybe it's possible to detect resumes and somehow try to figure out if the event tap has been lost? I'm happy to be a guinea pig if that helps. I'm hoping that Apple will eventually fix the problem (after they hopefully fix my second broken laptop), but until then... :-)

**Comment by aahung** [comment]
Normal sleep / resume should not be an issue, might be something abnormal. Detecting resume then recovering it might be a solution. Besides, since Unshaky is still running, it can also periodically check if the event tap is lost.

XD

**Comment by chmac** [comment]
Weird, it seems like now the computer has gone into this mode without a restart. No idea why. I'm getting repeated keys right now, and the <kbd>t</kbd> key is not being logged into the debug window. The modifier keys are being logged, but no keyboard press keys. I'm still running your special debug version. Not sure if the modifier keys being captured sheds any light on what's going on or not.

I also realise that unshaky must be working most of the time and killing a lot of duplicate keys, because I'm really noticing when it's broken! Thanks for this quick fix to an otherwise nightmare of a problem. ❤️

**Comment by chmac** [comment]
OK, I just restarted unshaky, and I'm still seeing the same behaviour. Only modifier keys get logged. So it looks like it's not actually an unshaky state, but somehow a MacOS state. Is there anything I can try to see what's causing this?

It looks like there are actually 2 issues here. One is fixed by an unshaky restart, and one is not. At first I think I got them confused into a single issue, but they now seem to be distinct. Or maybe the same cause, but sometimes a restart is not sufficient to fix it.

If there's anything I can do to help investigate while it's in this state, just let me know. 👍

**Comment by chmac** [comment]
Sorry about the wall of text. I've figured out one thing that's definitely happening repeatedly.

If I set the "ignore external keyboard" option to true, then no keys get captured.

I'm not running the latest 0.4.4 release.

Mac: MacBook Pro (15-inch, 2018)
MacOS: 10.14.3 (18D109)

Let me know if I can do anything else to help with this. If there is in fact still another separate issue going on, I'll open a new ticket if I can ever pin it down. For now, it looks like I can disable this option and unshaky works. 👍

**Comment by aahung** [comment]
> sometimes a restart is not sufficient to fix it

@chmac oops that will be hard to debug ...

> If I set the "ignore external keyboard" option to true, then no keys get captured.

@chmac can you turn off that option and try to type something and give me the debug output? with this version of Unshaky. [Unshaky_v0.4.5(31).zip](https://github.com/aahung/Unshaky/files/3020686/Unshaky_v0.4.5.31.zip) I think the 2018's MacBook has a different keyboard type due to the T2 security chip. Thanks and it will be a quick fix once I get the correct value!

**Comment by chmac** [comment]
Here's some debug output with ignore external keyboard set to off.

```

1553853122.398979 Key( 59| 17|             T|         0| 40) E(10)
1553853122.555707 Key( 59| 17|             T|         0| 40) E(11)
1553853128.480834 Key( 59| 17|             T|         0| 40) E(10)
1553853128.565616 Key( 59| 17|             T|         0| 40) E(11)
1553853128.740325 Key( 59| 15|             R|         0| 40) E(10)
1553853128.864378 Key( 59| 15|             R|         0| 40) E(11)
1553853130.131943 Key( 59| 16|             Y|         0| 40) E(10)
1553853130.252208 Key( 59| 16|             Y|         0| 40) E(11)
1553853152.488030 Key( 59| 15|             R|         0| 40) E(10)
1553853152.674686 Key( 59| 15|             R|         0| 40) E(11)
```

Does that help?

**Comment by aahung** [comment]
@chmac absolutely! "ignore external keyboard" is an easy fix thanks to you!

**Comment by aahung** [comment]
Closing it and move "stops working until restart" part to #39
