### ISSUE TITLE
Can you add a counter?

### ISSUE THREAD

**Issue by renziyao** [aahung/Unshaky#43]
Can you add a counter on the key which has been double clicked? We want to know how serious it is, so that we can repair it in the genius bar. 

Thank you.

**Comment by aahung** [comment]
you are talking about counting for individual keys right? Currently we have a counter but it is aggregating counts of all keys.

**Comment by renziyao** [comment]
Yes. That was exactly what I mean.

**Comment by jkeezy615** [comment]
Thanks again for creating this code, I can't tell you how much I appreciate it. Is it possible to view the aggregate counter for which keys are double clicking and how often?

**Comment by hadleyac** [comment]
I think that having a counter for the individual keys would be great as well.

**Comment by aahung** [comment]
Will work on it :-)

**Comment by Zandor300** [comment]
+1

**Comment by FemaleAutist** [comment]
I also think it'd be great to have individual key double press logs available! Would help fine tune the delays for different keys.

**Comment by aahung** [comment]
It will be in the next release :D

![image](https://user-images.githubusercontent.com/3804518/56847927-db3d4980-6914-11e9-9e3e-ffc97963e1b8.png)
