### ISSUE TITLE
'Unshaky' for Windows??

### ISSUE THREAD

**Issue by githmw** [aahung/Unshaky#44]
I read about your Mac program in a Wall Street Journal article. I think that is a very clever idea.

I use Windows7 PRO on my desktop. I use a very old KeyPro keyboard, which is great--much better than newer ones and with lots of customizable features. But a few of the keys have begun to double print, even though the key itself returns to the up position normally. There are no parts available for this keyboard. Your incorporation of killing any second signal within a specific time is great.

Do you perhaps make a version for Windows, or do you know of anyone who does? I am not a programmer, so I do not have the capability of modifying the open source code that you have posted.

Harry

**Comment by aahung** [comment]
A simpler version for Windows is feasible. I don't have a Windows machine so developing a Unshaky windows counterpart is hard for me. I found [a simple key map utility written in C](https://github.com/ililim/dual-key-remap) and I think it can be modified to prevent double key presses. I could play with it when I have time.

**Comment by aahung** [comment]
[this post](https://www.dell.com/community/Laptops-General-Read-Only/Keyboard-debouncing-utility-Solution-workaround-for-key-bounce/td-p/3487933) might help.

**Comment by githmw** [comment]
The links to KeybounceFilter no longer exist. AutoHotKey still exists, and there is some code for KeybounceFilter on on the AutoHotKey site. But I am no programmer, so have no idea how to use that code. Any suggestions or alternatives?

Harry
