### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by cperezabo** [aahung/Unshaky#45]
I think latest version is not working at all, it's not blocking anything and the debugger shows nothing

**Comment by aahung** [comment]
v0.4.5?

**Comment by aahung** [comment]
Thank you so much for reporting this... I made a silly mistake. If you turn on "ignore external keyboards" it will become useless... patching right now.

**Comment by aahung** [comment]
Please update it again, it should be fixed. Thanks @cperezabo !
