### ISSUE TITLE
Doesn't entirely work for my e key

### ISSUE THREAD

**Issue by xiaohanzai** [aahung/Unshaky#46]
**Is your feature request related to a problem? Please describe.**
This software really solves most of my problems. Thanks so much! However the double key press problem with my e key seems much more severe than other keys. I have already set the time delay to 80 ms and it still doesn't entirely work. Maybe there is a distribution of delay times with a long tail? Sometimes the second key press doesn't appear immediately, but it shows up after some other key press. For instance, if I type "set", it will probably become "sete".

**Describe the solution you'd like**
Perhaps the distribution of delay times can be taken into account, if there really is such a distribution... I'm not sure if there is another explanation for what I experienced with my e key.

**Describe alternatives you've considered**
I think I should just get my keyboard temporarily repaired...

**Additional context**

**Comment by aahung** [comment]
@xiaohanzai Can you try the "aggressive mode" from the setting? this seems to be a similar issue #29

**Comment by xiaohanzai** [comment]
Thanks! I just installed 0.4.7 and turned on the aggressive mode. Will wait and see.

**Comment by aahung** [comment]
reopen it if the issue persists.
