### ISSUE TITLE
Feature Requests: Disabling automatic update checks. -  Counter reset option.

### ISSUE THREAD

**Issue by hazar-e** [aahung/Unshaky#47]
*  an option for Disabling automatic update checks.

* option for reset counter ("Dismissed 940 shaky presses")

<img width="245" alt="Ekran Resmi 2019-04-02 03 59 30" src="https://user-images.githubusercontent.com/36481442/55368827-8caab400-54fc-11e9-9743-8ae0532aae0d.png">

**Comment by aahung** [comment]
> an option for Disabling automatic update checks.

Just found the update check interval is 1 day. I think it is too frequent, gonna change to 1 week by default. Auto updating for a software in early stage like Unshaky (has known bugs to fix and features to implement) is needed I think.

> option for reset counter ("Dismissed 940 shaky presses")

Sure. Also a hard reset button to reset everything.
