### ISSUE TITLE
i want translate to Turkish Language.

### ISSUE THREAD

**Issue by hazar-e** [aahung/Unshaky#48]
**Language**
Turkish

**Can you help with the translation?**
(Yes)

**Comment by aahung** [comment]
Hi @hazar-e thanks for your interest. A branch named "lang/tr" has been created and you can see 4 string files in [tr.lproj](https://github.com/aahung/Unshaky/tree/lang/tr/Unshaky/tr.lproj)

For each file you will see several `"some identifier here" = "some text in English here";` and only `"some text in English here"` part need translation. Besides, `/* ... */` are comments and they don't need translation.

Thanks!

**Comment by aahung** [comment]
Thank you @hazar-e for #53 ! Merged!
