### ISSUE TITLE
Russian/Ukrainian languages.

### ISSUE THREAD

**Issue by akhromets** [aahung/Unshaky#49]
**Language**
Russian, Ukrainian.

**Can you help with the translation?**
(Yes/No)
Yes

**Comment by aahung** [comment]
Hi @akhromets thanks for your interest. Two branches named "lang/ru" and "lang/uk" have been created and you can see 4 string files in either [ru.lproj](https://github.com/aahung/Unshaky/tree/lang/ru/Unshaky/ru.lproj) or [uk.lproj](https://github.com/aahung/Unshaky/tree/lang/uk/Unshaky/uk.lproj)

For each file you will see several `"some identifier here" = "some text in English here";` and only `"some text in English here"` part need translation. Besides, `/* ... */` are comments and they don't need translation.

Thanks!

**Comment by aahung** [comment]
Thank you @akhromets for #51 and #52, both merged!
