### ISSUE TITLE
Configure window only stays open for a fraction of a second

### ISSUE THREAD

**Issue by doubleosixandahalf** [Aahung/Unshaky#5]
When i try and open the configure window it only flashes open and then is gone. I cant modify the settings of the app

**Comment by Aahung** [comment]
That's odd, can you check if the window still exists but covered by other windows (using mission control)?

 What is your OS version? Does the App also exit or crash?

If possible, can you open the "Console" App (built in app on your Mac) and search "Unshaky" to see if there is any log related?

**Comment by doubleosixandahalf** [comment]
Hi,

I checked mission control Unshaky is not there.

OS Version 10.12.6

The app doesn't appear to do anything, I have a icon for unshaky on the top of my screen.

output of log from console:

[Unshaky pid:10927 mux-aware] starting, non-mux-aware app count 0, switch-state 0 IG FBs 1 EG FBs 0:0 power-state 6 3D idle HDA idle

[NowPlayingTouchUI] Reloading available apps due to workspace activating an application: NSConcreteNotification 0x618000241950 {name = NSWorkspaceDidActivateApplicationNotification; object = <NSWorkspace: 0x60800001b700>; userInfo = {
    NSWorkspaceApplicationKey = "<NSRunningApplication: 0x61800011c830 (com.nestederror.Unshaky - 10927)>";
}}

**Comment by Aahung** [comment]
Thanks for the info. I thought it was due to the system version so I created a virtual machine and just triggered this bug in 10.12.6. 

Looking into the issue.

**Comment by Aahung** [comment]
Try [v0.2.1](https://github.com/Aahung/Unshaky/releases/tag/v0.2.1)
