### ISSUE TITLE
Alfred auto expansion doesn't work as smoothly as it used to

### ISSUE THREAD

**Issue by martisj** [aahung/Unshaky#54]
**Describe the bug**
Auto expanding snippets in Alfred replay a bunch of key strokes at a blazing rate, however this conflicts with unshaky. So I guess it's more of a feature request maybe?

**To Reproduce**
1. Make an auto expandable snippet in Alfred
2. Set the expansion speed to the slowest
3. Expand the snippet and see that only part of it is removed again afterwards.

**Expected behavior**
Snippet is expanded and keyword is removed.

**Desktop (please complete the following information):**
 - macOS version: 10.14.3
 - Unshaky version 0.4.6

**Comment by aahung** [comment]
I will try to monitor Alfred's auto expansion to see whether I can whitelist it.

**Comment by aahung** [comment]
@martisj the solution I found is to disable Unshaky for the `Delete` key...

**Comment by aahung** [comment]
I found another workaround, and it should work when Alfred's "simulated key event speed" set to "Fastest". Will release this version soon.

**Comment by martisj** [comment]
Thank you so much for looking into and fixing this issue!
