### ISSUE TITLE
support different keys

### ISSUE THREAD

**Issue by calphool** [aahung/Unshaky#55]
It would be nice if unshaky could be configured to remove OTHER characters other than double strokes.  When a mac keyboard starts acting up, sometimes it types other keys that are in the same row, not just the one you are pressing.  For example, if you press J, sometimes it double presses J, but it may also type JAK because A and K are in the same row.

**Comment by aahung** [comment]
@calphool I am afraid it is not something software can do easily, since it is nearly impossible to tell whether "A/K" is intended or not.
