### ISSUE TITLE
Interferes with Dash snippet expansion

### ISSUE THREAD

**Issue by Kapeli** [aahung/Unshaky#58]
This is related to https://github.com/aahung/Unshaky/issues/54, feel free to close it and handle it as a duplicate.

Dash sometimes relies on sending keystroke events repeatedly when expanding snippets. These events are only backspaces and arrow keys.

When these events happen, the pasteboard has the "org.nspasteboard.TransientType" maker (see http://nspasteboard.org). Could you maybe check the pasteboard for this marker and disable Unshaky temporarily while that marker is present? 

Alternatively, could you think of any way I could prevent Unshaky from dropping my events? Or maybe just check if Dash is installed and show a warning that Dash snippet expansion might not work when the user enables Unshaky for the arrow and/or backspace keys.

**Comment by aahung** [comment]
Hey @Kapeli thanks for the insight related to #54. Can you elaborate it a little more? When you trigger the expansion, does Dash send `N * backspaces` and simulate the typing of another string very quickly? When is the pasteboard set with "org.nspasteboard.TransientType" maker? And will the marker be deleted when expansion complete?

**Comment by Kapeli** [comment]
> When you trigger the expansion, does Dash send `N * backspaces` and simulate the typing of another string very quickly?

Dash only sends backspaces and arrow keys. It doesn't simulate typing the string. This only happens in non-accessible apps (e.g. Sublime Text). In accessible apps snippet expansion doesn't require any key presses.

> When is the pasteboard set with "org.nspasteboard.TransientType" maker? And will the marker be deleted when expansion complete?

The marker is set right before Dash starts expanding the snippet and gets deleted after expansion completes. You can also set it up so that you only disable Unshaky for ~2-3 seconds of detecting the pasteboard marker, since expansion doesn't take too long.

**Comment by aahung** [comment]
@Kapeli I think it is feasible. I looked around and there does not seem to be a passive way to detect the occurrence of such marker. 

> Unfortunately the only available method is by polling (booo!). - https://stackoverflow.com/a/5033480/2361752

And another workaround is when Unshaky is about to dismiss a key, it checks the pasteboard. But it will have a hit on CPU. Do you think we can build a channel, and when Dash is going to expand something, to disable Unshaky temporarily? (e.g., let Unshaky handle some URL)

**Comment by aahung** [comment]
@Kapeli I also have another idea. I just wonder if it is possible to send the key event with a different `keyboardType` other than `58/59`, then it is very easy for Unshaky to whitelist Dash. 

https://github.com/aahung/Unshaky/blob/master/Unshaky/ShakyPressPreventer.m#L105

**Comment by Kapeli** [comment]
That would be great and easy to add on my end. Any idea what keyboard type should I use? They don't seem to be documented anywhere.

**Comment by aahung** [comment]
@Kapeli Can you give me some sample codes that send those keyboard events? so that I can play with it.

**Comment by aahung** [comment]
@Kapeli if you are using `CGEventCreateKeyboardEvent()` to create keyboard event, you can use 

[`setIntegerValueField(_:value:)`](https://developer.apple.com/documentation/coregraphics/cgevent/1455556-setintegervaluefield) to set `kCGKeyboardEventKeyboardType` to something other than 58 or 59.

**Comment by Kapeli** [comment]
Yep, I'm using `CGEventCreateKeyboardEvent`. I was asking what I should set `kCGKeyboardEventKeyboardType` to, since the actual values aren't documented anywhere. I'll experiment with it.

**Comment by aahung** [comment]
Oh. I didn’t find any documents either. 58 is for 16-17 and 59 is 2018 models according to users’ reports

**Comment by aahung** [comment]
@Kapeli If Dash sends all those events within 5ms, v0.5.0 will ignore them. Maybe it is enough to resolve the conflict.

**Comment by aahung** [comment]
@Kapeli does the new version have conflict with Dash?

**Comment by Kapeli** [comment]
I'm able to replicate the issue with Unshaky 0.5.2. Seems to be the same as 0.4.8.

**Comment by aahung** [comment]
@Kapeli 

I download Dash and experimented myself, it looks like Dash sent "Delete" keys ~10ms after another. And the `keyboardType` is set to "58" on my MacBook Pro 2016. Wonder whether you have a sleep-for-10ms between two DELETE events? When I increase the threshold (mentioned above) to 15ms, Dash's expansion works 100% of the time. 

```
1556538952.332929 Key( 46|  2|             D|         0|200) E(10)
1556538952.340509 Key( 46|  0|             A|         0|200) E(11)
1556538952.344524 Key( 58| 51|        Delete|         0|200) E(10)
1556538952.344707 Key( 58| 51|        Delete|         0|200) E(11)
1556538952.357897 Key( 58| 51|        Delete|         0|200) E(10) DISMISSED
1556538952.358221 Key( 58| 51|        Delete|         0|200) E(11) DISMISSED
1556538952.365654 Key( 58| 51|        Delete|         0|200) E(10) DISMISSED
1556538952.366060 Key( 58| 51|        Delete|         0|200) E(11) DISMISSED
1556538952.380290 Key( 46|  1|             S|         0|200) E(11)
1556538952.380475 Key( 58|  9|             V|   1048576|200) E(10)
1556538952.380620 Key( 58|  9|             V|   1048576|200) E(11)
1556538952.444605 Key( 46|  2|             D|         0|200) E(11)
```

**Comment by Kapeli** [comment]
Yes, I have a delay between events. It's needed by some apps.

I'll experiment with setting a different `keyboardType` for the next Dash update. Not sure when I'll get to it though.
