### ISSUE TITLE
Update checking broken

### ISSUE THREAD

**Issue by Zandor300** [aahung/Unshaky#59]
**Describe the bug**
When checking for updates, it says it's up-to-date while it isn't:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/6069593/56140969-3299fc00-5f9c-11e9-8ccc-ffbda383fd34.png">

**To Reproduce**
1. Click Check for updates from the menubar menu.

**Expected behavior**
It should say there is an update available. 0.4.8 is available.

**Desktop:**
 - macOS version: 10.14.4
 - Unshaky version: 0.4.6

**Comment by aahung** [comment]
@Zandor300 Thanks, it turns out I forgot to update the feed.

**Comment by tbradsha** [comment]
Same issue in 0.5.0 (0.5.2 is out now).

**Comment by aahung** [comment]
@tbradsha updated, thanks!
