### ISSUE TITLE
Space key not being delayed.

### ISSUE THREAD

**Issue by mahmai** [Aahung/Unshaky#6]
I can add delay for other keys and it's working fine but not for the `space` key. Even if I added a long delay say _5000_ and press the `space` many  times, it  won't block it.

**Comment by Aahung** [comment]
I should have removed that workaround since the latest version is capable to manage each key individually. Before I update the code, can you try [0.1.1](
https://github.com/Aahung/Unshaky/releases/tag/v0.1.1) to see if you have the same issue as #1?

**Comment by mahmai** [comment]
Yes currently I am using that version and changed key-map for spotlight as `cmd + space` doesn't work.

**Comment by Aahung** [comment]
So you also have the issue #1. What is your OS version?

**Comment by mahmai** [comment]
Space is not being delayed on [0.2.1](https://github.com/Aahung/Unshaky/releases/tag/v0.2.1). So, I installed [0.1.1](https://github.com/Aahung/Unshaky/releases/tag/v0.1.1)  knowing it has issue #1. I am using `macOS High Sierra 10.13.6 (17G65)`

**Comment by Aahung** [comment]
That's odd, same as mine. 

@mahmai I created another release [v0.2.2](https://github.com/Aahung/Unshaky/releases/tag/v0.2.2) and unlock the space key. Maybe you need to change the spotlight shortcut temporarily, and I need to find a Mac (in real life) that has such issue to test more.

**Comment by Aahung** [comment]
BTW, I use right option key for spotlight, you can give a try, very convenient.

**Comment by Aahung** [comment]
Oh you can remap the keys using some other apps.

I created a macOS 10.13.6 VM and still could not make the issue appear. No luck seems...
