### ISSUE TITLE
Italian language translation

### ISSUE THREAD

**Issue by valepert** [aahung/Unshaky#60]
**Language** Italian

**Can you help with the translation?**
(Yes/No) Yes

**Comment by MarcoCarnevali** [comment]
I'm available too

**Comment by aahung** [comment]
Hi @valepert @MarcoCarnevali  thanks for your interest. A branch named "lang/it" has been created and you can see 4 string files in "it.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

Thanks!
