### ISSUE TITLE
Portuguese (Portugal) Translations

### ISSUE THREAD

**Issue by GoncaloCdM** [aahung/Unshaky#61]
**Language**
Portuguese (Portugal)

**Can you help with the translation?**
Yes

**Comment by aahung** [comment]
Hi @GoncaloCdM  thanks for your interest. A branch named "lang/pt-PT" has been created and you can see 4 string files in "pt-PT.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

Thanks!

**Comment by GoncaloCdM** [comment]
Translations completed.
