### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jadraker** [aahung/Unshaky#63]
**Language**
Spanish.

**Can you help with the translation?**
(Yes/No)
Yes.

**Comment by aahung** [comment]
@jadraker thanks for your interest. Which of the below should I choose?

- Spanish (es)
- Spanish (Latin America) (es-419)

**Comment by jadraker** [comment]
Hi,
Spanish Latin America es-419.

**Comment by aahung** [comment]
Hi @jadraker  thanks for your interest. A branch named "lang/es-149" has been created and you can see 4 string files in es-149.lproj

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

Thanks!

**Comment by jadraker** [comment]
Hi @aahung,
Please tell me if I translated the first file as it should: https://github.com/aahung/Unshaky/compare/lang/es-419...jadraker:patch-1.

Thank you and congratulations for this software. I hope 2019 and future Mac implement a butterfly or another more reliable keyboard. I've had two MBP 2018 with same problems.

**Comment by aahung** [comment]
Translation seems good, just need it to the line below. For example, line 3 instead of line 2. Line 2 is actually just comment and you can leave it there.

So annoying you have two Mac being affected ...

**Comment by jadraker** [comment]
Hi @aahung,
The 4 files you requested were translated into Spanish LA. 
Please tell me if it's okay (I translated the 4 files again correcting the problem with the comments).
What are the following steps to see this translation go live? :)

Thank you.

**Comment by aahung** [comment]
Thanks! Did you create a pull request?
I will test it a bit to ensure the UI looks good, and it will go live in the next version.

**Comment by aahung** [comment]
@jadraker I already merged your translation, there is nothing left for you to do. Thank you!
