### ISSUE TITLE
Portuguese (Brazil) translation

### ISSUE THREAD

**Issue by delissonjunio** [aahung/Unshaky#64]
**Language**
Portuguese (Brazil)

**Can you help with the translation?**
Yes

**Comment by aahung** [comment]
Hi @delissonjunio   thanks for your interest. A branch named "lang/pt-BR" has been created and you can see 4 string files in "pt-BR.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

Thanks!

**Comment by aahung** [comment]
Branch "lang/pt-BR" is out of sync with master branch. Close it for now.

**Comment by delissonjunio** [comment]
Hi @aahung sorry I never followed up on here, did not get the notification at the time and forgot about it. Can you recreate that branch again? Thanks!

**Comment by aahung** [comment]
@delissonjunio great to hear back from you! I have recreated the branch with the latest string files.

**Comment by delissonjunio** [comment]
@aahung changes are made and the branch is pushed, should I just open a PR now?

**Comment by aahung** [comment]
@delissonjunio yeah plz. thx
