### ISSUE TITLE
Keeweb auto-expansion skips letters

### ISSUE THREAD

**Issue by tbradsha** [aahung/Unshaky#65]
**Describe the bug**
Keeweb (a password manager) has a shortcut that auto-fills usernames/passwords into fields, but this process omits letters when Unshaky is enabled.

**To Reproduce**
1. Add a username/password in Keeweb.
2. Navigate to that account login page in a browser.
3. Press Ctl-Option-T to trigger auto-fill.
4. See missing letters, resulting in a failed login.

**Desktop (please complete the following information):**
 - macOS 10.14.4
- Unshaky v0.4.8
- Keeweb v1.8.1

**Additional context**
Likely the same issue as #54.

**Comment by aahung** [comment]
From I can tell from the [Keeweb's source code](https://github.com/keeweb/keeweb/blob/26d6844b65e78217d3b3eb6cfa4ed5e226404320/helper/darwin/src/KeeWebHelper/InputCommands/SendTextCommand.m#L30), it simulates the press of password in a very short time. I think [this commit](https://github.com/aahung/Unshaky/commit/dfa2b96748c918fb15453da9829783f1e4d37615) can ignore such press sequence. Please try the v0.5.0 (will be online in a few minutes.)

**Comment by tbradsha** [comment]
Looks like that did it for me!

**Comment by aahung** [comment]
great!

**Comment by tbradsha** [comment]
After using the latest version for the last week or two, it seems to work most of the time, but not every time. Is there a way you can raise the ignore threshold slightly or perhaps allow the end user to do that?

**Comment by Zandor300** [comment]
You can modify the delay yourself in settings.

**Comment by tbradsha** [comment]
I see we can modify the delay for each key, but I don't see a way to increase the AUTO_EXPANSION_IGNORE_THRESHOLD beyond 5ms in the settings?

**Comment by aahung** [comment]
I will make it customizable later. It is a imperfect workaround :-(
