### ISSUE TITLE
Debug window is always empty.

### ISSUE THREAD

**Issue by mahmai** [Aahung/Unshaky#7]
The debug window is always displaying an empty window.
<img width="400" alt="screen shot 2018-07-25 at 10 28 40 am" src="https://user-images.githubusercontent.com/16437807/43185781-8ef01bc8-8ff5-11e8-9ed6-761cf8bc8676.png">

**Comment by mahmai** [comment]
I see it was opening a new debug window every time I  click `open debug window`.

**Comment by Aahung** [comment]
Also It only display log of keys enabled in the configuration.

**Comment by daniellivingston** [comment]
+1. I'm experiencing this same issue as well running v0.4.3 on macOS Sierra.

**Comment by aahung** [comment]
@daniellivingston sorry I didn't see your comment until now. Have you set the delays for any keys? The debug window only shows events of keys you set delays to non-zero values.

**Comment by daniellivingston** [comment]
I have, quite a few keys are set. Note that the status icon says "Dismissed 342 shaky presses". And the core program is working wonderfully! It is only the debug pane that fails to load.

**Comment by daniellivingston** [comment]
## Status bar icon:

<img width="124" alt="Screen Shot 2019-03-15 at 12 20 23 PM" src="https://user-images.githubusercontent.com/20751300/54453365-c74ed700-471c-11e9-97dc-638f39e45af1.png">

## Debug pane:

<img width="616" alt="Screen Shot 2019-03-15 at 12 20 32 PM" src="https://user-images.githubusercontent.com/20751300/54453358-c322b980-471c-11e9-87c5-c6335a8cac89.png">

**Comment by aahung** [comment]
@daniellivingston Let's say you set the day of "a" to 100ms. Open the debug window and press "a," is there anything?

**Comment by daniellivingston** [comment]
Done - no, unfortunately there is not. Still blank.

<img width="335" alt="Screen Shot 2019-03-15 at 12 23 07 PM" src="https://user-images.githubusercontent.com/20751300/54453535-23b1f680-471d-11e9-98b5-993df407a279.png">

**Comment by aahung** [comment]
That might have something to do with Sierra (I did all testing on Mojave)
In [v0.4.4](https://github.com/aahung/Unshaky/releases/tag/v0.4.4) I changed the way how debug window is opened. Can you give it a try?

**Comment by daniellivingston** [comment]
On v0.4.4, I tried typing a few sentences and verified that additional key presses were captured, but still no dice:

<img width="610" alt="Screen Shot 2019-03-15 at 12 37 38 PM" src="https://user-images.githubusercontent.com/20751300/54454489-30cfe500-471f-11e9-8155-9f10bd45a21f.png">

**Comment by aahung** [comment]
Thanks for doing these tests! I don't have a Sierra development environment to find out what is going... I opened a new issue #42 and keep it open for now. Sorry for the inconvenience.

**Comment by aahung** [comment]
@daniellivingston Can you try this version, I don't have a Sierra to test it. Thanks!

[Unshaky_v0.4.5_beta.zip](https://github.com/aahung/Unshaky/files/2981019/Unshaky_v0.4.5_beta.zip)
