### ISSUE TITLE
Indonesian Translation

### ISSUE THREAD

**Issue by elmotan95** [aahung/Unshaky#70]
**Language**
Indonesian

**Can you help with the translation?**
Yes

**Comment by aahung** [comment]
Hi @elmotan95 thanks for your interest. A branch named "lang/id" has been created and you can see 4 string files in id.lproj

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

Thanks!
