### ISSUE TITLE
Escaping the delayed character

### ISSUE THREAD

**Issue by mahmai** [aahung/Unshaky#73]
A keystroke for a delayed key is not being sent after a non delay key is pressed.

For Example As my 'e' key is very sensitive It woks fine when delayed for say 250ms and if I want to type 'eye', only 'ey' is being typed. I think there is no mechanism where you make a reset for the timer if another key is pressed. I think the issue is the keystoke 'e', is still being delayed even is I typed 'y' after 'e'. I dont know if I explained it well.

**Comment by aahung** [comment]
That’s the intended behavior. The figure below might be able to illustrate it.
![IMG_1697](https://user-images.githubusercontent.com/3804518/56624108-fb95ab80-6669-11e9-8d22-478ef490ce2a.png)

**Comment by aahung** [comment]
250ms is too large a delay value, you can start with 50ms and increase it if needed.

**Comment by mahmai** [comment]
Oh. I see. But, I think mine is very sensitive and it sends multiple key stokes at once like 4 'e's or Something like that. I think it is beyond the control of a software. I may have to look for a hardware solution. Thank you!

**Comment by aahung** [comment]
@mahmai try to turn on `aggressive mode` in setting. It might help with your case.

**Comment by mahmai** [comment]
@aahung Will try that. Thanks Again
