### ISSUE TITLE
Add localisation for Dutch (nl)

### ISSUE THREAD

**Issue by siebrand** [aahung/Unshaky#74]
Please add localisation for Dutch. I will submit the translated strings in a pull request. I don't know how to add the glue.

**Comment by aahung** [comment]
Thanks! @siebrand don't worry leave it to me.

**Comment by aahung** [comment]
Thanks!

**Comment by aahung** [comment]
theat revert thing was my mistake...

**Comment by siebrand** [comment]
I submitted a pull request to fix, and also updated the missing translations from the strings you added.

**Comment by aahung** [comment]
thank you @siebrand merged!
