### ISSUE TITLE
Localizable.strings "Paste Configuration here" not localized

### ISSUE THREAD

**Issue by siebrand** [aahung/Unshaky#80]
**Describe the bug**
In version 0.5.3, there is a translation present for Localizable.strings "Paste Configuration here" in Dutch (nl), but this is not visible in the UI. I'm not sure how to check if this may be the same in other languages. This particular string is also translated in Japanese and Korean.

**To Reproduce**
Steps to reproduce the behavior in a macOS with Dutch UI:
1. Go to 'Settings'. A new dialog window opens.
2. Click on 'Import'. A dialog window opens inside the previous dialog.
3. This dialog contains the text "Paste the configuration here"

**Expected behavior**
Expected is that the dialog contains the text "Plak hier de instellingen"

**Desktop (please complete the following information):**
 - macOS version: 10.14.4

**Additional context**
I think this has to do with a string in Base.lproj/Localizable.strings not being consistent with the string in the code. I will submit a patch.

**Comment by aahung** [comment]
Thank you @siebrand :D

**Comment by siebrand** [comment]
Confirmed fixed in 0.5.4.
