### ISSUE TITLE
Button size too small for some languages

### ISSUE THREAD

**Issue by Zandor300** [aahung/Unshaky#82]
**Describe the bug**
The "Set" button in settings is too small for some languages, such as Dutch.

**To Reproduce**
- Start Unshaky with Dutch as the primary macOS language.
- Go into settings and look.

**Expected behavior**
Button text should be the same size as on English.

**Potential solution**
Making the button wider would solve this problem. The textfield doesn't have to be this big so making room wouldn't be a problem.

**Screenshots**
<img width="592" alt="image" src="https://user-images.githubusercontent.com/6069593/57183046-a64a6d00-6ea7-11e9-9b3a-324aa3296938.png">

**Environment**
 - macOS version: 10.14.4 (18E226)
 - Unshaky version: 0.5.3

**Comment by aahung** [comment]
![image](https://user-images.githubusercontent.com/3804518/57212253-03255080-6f98-11e9-86d3-8ff4fd1d96ff.png)
is this better?

**Comment by Zandor300** [comment]
Yes thanks!

**Comment by aahung** [comment]
:D
