### ISSUE TITLE
Russian Language keyboard support...

### ISSUE THREAD

**Issue by dgraid** [aahung/Unshaky#83]
My macbook pro 2018 keyboard is also broken, but i use russian language, and can't setup the app to help me support my language.
I don't talk about app translation - english is ok.

Can you please add other languages (russian) support for your nice app?

**Comment by Zandor300** [comment]
@aahung I don't know how you are specifying the keys, but maybe use macOS APIs to get keys for every keyboard layout supported in macOS? Maybe make it possible to set keys per keyboard layout and then get the settings for the current layout and those keycodes.

https://support.apple.com/en-us/HT201794
https://github.com/Clipy/Sauce
https://stackoverflow.com/questions/3202629/where-can-i-find-a-list-of-mac-virtual-key-codes/16125341

**Comment by aahung** [comment]
Thanks for the links. I explored a little bit more and found an API that might help to [translate key code to string supporting different keyboard layouts](https://developer.apple.com/documentation/coreservices/1390584-uckeytranslate?language=objc). However, it is using Carbon and it is expected not to run on next version of macOS (several months later). I am probably just hardcode the strings into Unshaky. Do you know where I can get a map for Russian like [this https://gist.github.com/eegrok/949034](https://gist.github.com/eegrok/949034)?

**Comment by Zandor300** [comment]
You could just loop through all `UInt16`'s on the Russian keyboard layout using that function (`UCKeyTranslate`) and then hardcode the output?

**Comment by dgraid** [comment]
Sorry, i checked, i think it works!! i just switched language and tested the buttons = it works in russian buttons!! Thank you so much!!!

**Comment by Zandor300** [comment]
Wut?

**Comment by dgraid** [comment]
My issue is ok, no problem

**Comment by aahung** [comment]
I am gonna re-open this issue because Russian characters are not displayed in Preference panel after all. 

I manually typed these keys with Russian virtual keyboard and get this, are these all the difference between a US keyboard and a Russian keyboard?

```
@0: @" Ф", // <-> A
@11: @" И", // <-> B
@8: @" С", // <-> C
@2: @" В", // <-> D
@14: @" У", // <-> E
@3: @" А", // <-> F
@5: @" П", // <-> G
@4: @" Р", // <-> H
@34: @" Ш", // <-> I
@38: @" О", // <-> J
@40: @" Л", // <-> K
@37: @" Д", // <-> L
@46: @" Ь", // <-> M
@45: @" Т", // <-> N
@31: @" Щ", // <-> O
@35: @" З", // <-> P
@12: @" Й", // <-> Q
@15: @" К", // <-> R
@1: @" Ы", // <-> S
@17: @" Е", // <-> T
@32: @" Г", // <-> U
@9: @" М", // <-> V
@13: @" Ц", // <-> W
@7: @" Ч", // <-> X
@16: @" Н", // <-> Y
@6: @" Я", // <-> Z
@10: @"SectionSign",
@50: @"]", // <-> Grave `
@27: @"Minus",
@24: @"Equal",
@33: @"х", // <-> LeftBracket [
@30: @"ъ", // <-> RightBracket ]
@41: @"ж", // <-> Semicolon ;
@39: @"э", // <-> Quote '
@43: @"б", // <-> Comma ,
@47: @"ю", // <-> Period .
@44: @"Slash",
@42: @"ё", // <-> Backslash \
```

**Comment by dgraid** [comment]
Yes that is!

**Comment by aahung** [comment]
@dgraid Can you go to debug window and verify the keyboard code for `]` is 50? key code is the second number enclosed by parenthesis "()"

```
@50: @"]", // <-> Grave `
```

Since I found the virtual keyboard (provided by macOS) is not the same as I found on [Apple website](https://support.apple.com/en-us/HT201794):

![image](https://user-images.githubusercontent.com/3804518/57410343-659c6d80-719f-11e9-9335-dcd3c441a8ea.png)

**Comment by dgraid** [comment]
1557410095.592396 Key( 59| 30|  RightBracket|         0| 40) E(10)
1557410095.693385 Key( 59| 30|  RightBracket|         0| 40) E(11)
