### ISSUE TITLE
List of problematic keys

### ISSUE THREAD

**Issue by Saxintosh** [aahung/Unshaky#84]
What about a log of the keys that have been fixed?
To find out which keys may require cleaning or which are more defective.

**Comment by Zandor300** [comment]
Do you mean; a list of keys that might require the user to set up unshaky for? So actually double press detection on all keys but instead of blocking, log that that key might require blocking to inform the user and give feedback on their configuration?

**Comment by Saxintosh** [comment]
Just a kind of statistic that lets you know which double press have been detected and fixed.
For example, I know that I have problems with 'enter', 'm', 'd' and 'del' keys. Probably also 'space' key. 
I don't know if I have other problematics keys and I don't know which keys are most frequently fixed.

**Comment by aahung** [comment]
Usually people uses Unshaky the other way around.

1. they discovered some key has double-press issue
2. Configure delays for that key

So you don't have to configure delays for keys that are fine. 

For the statistics, you can click the first menu item to see how many times Unshaky blocks each key with delays configured.

**Comment by Saxintosh** [comment]
Hi aahung,
the "other way around" is fine and is the same way that I use.

But usually, when you realize you have a keyboard problem and find out you can use Unshaky, you install it as soon as possible. Then you can't tell which keys have a problem. The application works beautifully and that's it!

Later, it would be useful to know which keys have problems for two reasons:
1- you might want to try cleaning the keyboard by blowing air on the defective keys.
2- if you go to Apple to try to change the keyboard, they ask you which keys don't work because they will try to clean them first and only then to change the keyboard.

**Comment by aahung** [comment]
:D

I think might have configured delays for all keys as a precaution. In that case, there is a statistics view (open by click "Prevent shaky presses * times) showing each key's suspect double press count. It does not necessarily indicate the ground truth, but only defective keys are likely to have positive counts. 

Hope it works for you!

**Comment by Saxintosh** [comment]
"Dismissed x shaky presses"
wow!!! It's exactly the statistical page that I was looking for!!!
Thanks!
I've never thought of clicking on that menu item... I thought it was just an information line, but it opens the statistics window!
:-D
Perfect!!!

**Comment by aahung** [comment]
@Saxintosh whether it is truly defective still need your own judgement though. :las

**Comment by aahung** [comment]
u

**Comment by Saxintosh** [comment]
Maybe you could change the name of that menu item... "Statistics" seems perfect :-D :-D

**Comment by aahung** [comment]
Maybe putting a little ℹ️ button after "dismissed..." is adequate.

**Comment by aahung** [comment]
I made it "☚ Dismissed x shaky presses...", hope it is enough to indicate its click-ability. Let's see. :D

**Comment by Saxintosh** [comment]
I think it's perfect! :-)
