### ISSUE TITLE
Could a similar solution be found for keys that don't register presses? 

### ISSUE THREAD

**Issue by jtheletter** [aahung/Unshaky#85]
This app has been surprisingly useful in preventing my brand-new MacBook keyboard's doubling of keypresses, and I thank you for that. Apple is a joke lately. 

I wonder if a similar approach could solve my left-side command key that barely registers keypresses? I need to slam it or press it perfectly center to register, and this is arguably the key I use the most. 

Thank you.

**Comment by aahung** [comment]
Unfortunately, that is beyond a software solution since there won't be any signals to work with.
