### ISSUE TITLE
Set Unshaky in read-only mode

### ISSUE THREAD

**Issue by jeffreytigch** [aahung/Unshaky#86]
**Is your feature request related to a problem? Please describe.**
Now Apple has extended their keyboard repair program, I would like to know if and when unintentional keys are being hit or missed.

**Describe the solution you'd like**
A switch, where I can disable Unshaky's assistance, but keep the info Unshaky gathered. In an ideal situation, I would be able to get a log with which button had an unintentional key press and when that occurred, so I can troubleshoot and send that info over to the repair shop.

**Describe alternatives you've considered**
Keeping Unshaky enabled. Would have to check periodically and currently not able to see which keys are having problems.

**Comment by aahung** [comment]
Unshaky already provides troubleshooting information, labelling events as "DISMISSED" in the log, which is a symptom of defective keys. If you want to have an overview, click the "Dismissed X shaky key presses".

**Comment by jeffreytigch** [comment]
I get that, but the debug window isn't always open. It can troubleshoot just fine when trying live, but it doesn't build an history of occurrences.

f I would look into my use case, my keyboard is already replaced, and I would like to monitor if this happens again. The counter can't be reset at the moment and opening the debugging window for the next year isn't really an ideal solution for that. 

Anyhow, might be an enhancement if you or anyone else have some downtime.

**Comment by aahung** [comment]
Oh kind of understood what you try to do. 

> but it doesn't build an history of occurrences.

Unshaky does have a counter for individual key, does it provide the info you need?

> The counter can't be reset at the moment

There is a reset button in the aforementioned statistic window, which can be opened by clicking Unshaky's first menu item "Dismissed X shaky presses"

**Comment by jeffreytigch** [comment]
I never realised the "Dismissed X shaky presses" is clickable. Does what I currently need. Thanks for the info! You could keep this issue open if you want to, but my question/request is answered.

**Comment by aahung** [comment]
@jeffreytigch you are not the first one getting confused, I probably need to make some UI changes  see #84
