### ISSUE TITLE
Turkish keyboard support

### ISSUE THREAD

**Issue by hazar-e** [aahung/Unshaky#87]
Unshaky 0.5.4 - Macbook Pro 2016 touchbar

I can't assign some turkish keys. for example (Ü, Ö Ç). Will it be compatible with all keyboard types in the future ?
here is my keyboard

<img width="733" alt="Ekran Resmi 2019-05-25 18 42 35" src="https://user-images.githubusercontent.com/36481442/58371901-99f18700-7f1e-11e9-90ea-3718eb0c7b9a.png">

**Comment by aahung** [comment]
I guess I just add the layout one by one when someone request it.
