### ISSUE TITLE
Has Apple fixed this?

### ISSUE THREAD

**Issue by dfdy** [aahung/Unshaky#88]
**Describe the bug**
This is not a bug report, but a request for confirmation/information. 

Some time in the last month or two the keyboard on my MBP 13" Touch Bar (mid 2018) - which had gotten quite bad - stopped having any repeating keys!! I did not notice the change right away, since Unshaky usually does a great job of preventing repeat keys. I finally have a period when I can take my MBP in for repairs, and decided to unload Unshaky and see how bad the problem had gotten, before going to the shop. No repeat keys!!

I recall installing a MacOS update a few weeks ago. Could Apple have fixed the problem in software? Am I the only person with a magically self-repairing keyboard? 

I would like to have this confirmed so that I can rule out an intermittent keyboard problem before my warranty runs out. 

**To Reproduce**
Update to latest MacOS: 10.14.5 (18F132) (Install all available updates.)
Unload Unshaky. 
Type stuff.

**Expected behavior**
Broken keyboard should be broken. ¯\_(ツ)_/¯

**Desktop (please complete the following information):**
 - macOS version: 10.14.5 (18F132)

**Comment by Zandor300** [comment]
I believe your MacBook falls under the free repair program. You can create an appointment on the Apple Support site for free. I went into the Apple Store and they cleaned out my worst keys for free as a service and now the double press occurrence has greatly been reduced.

The service program is only valid for the 4 years after the purchase date. Your entire top chassis will be replaced if you go through with it (including touchbar, battery, speakers, trackpad). **You can only do this for free once!**

This is what the guy from the Apple Store told me. If this isn't true, blame that guy, not me.

**Comment by dfdy** [comment]
Hi. I am actually looking for anyone to confirm whether or not Apple have implemented a software fix as I have 0 dismissed keys now, and I used to have a few hundred per day in the past. 

(I will look into the 4-year free repair program, however I do not believe Apple will have this in my country, South Africa).

**Comment by Zandor300** [comment]
Here is the Keyboard Repair Program page, you can check for yourself:
https://www.apple.com/support/keyboard-service-program-for-mac-notebooks/

Regarding the original topic: I just checked an I was running 10.14.5 (18F132) even before the cleaning by Apple on my keyboard. For the record; I'm still seeing double presses and before the cleaning even experienced rare quadruple presses.

**Comment by aahung** [comment]
@dfdy I am not sure. It is not likely since I don't see any news. The keyboard itself is unstable, yours could possibly fix itself somehow :-D

**Comment by aahung** [comment]
@Zandor300 not sure if "for free once" is a practice for all apple store. I think (hopefully) they will fix it when we have the problem again. replacing the top case has a bonus new battery, which I really appreciate

**Comment by domcorvasce** [comment]
Nope, Apple has not corrected the problem via software (I, too, own a MBP 2018).
I hope the 4th generation keyboard is going to fix all the issues, but the reality seems more pessimistic.

I see some issues with Apple releasing an official substitute to Unshaky, directly in macOS:

- everyone types at a different speed, they wouldn't able to hide the software because users would need a menu to configure the delay for each key.

- it would be a PR nightmare, admitting that they screwed up so much that their only solution is a software one.

**Comment by aahung** [comment]
@domcorvasce thanks for sharing your experience. I am gonna close this issue.
