### ISSUE TITLE
Updater doesn't find the new release (5.5)

### ISSUE THREAD

**Issue by domcorvasce** [aahung/Unshaky#89]
**Describe the bug**

Whenever I check for updates, Unshaky tells me that I am using the latest version (5.4) but from the releases section I see that 5.5 is available.

**To Reproduce**
1. Go to 'Check for updates...'

**Expected behavior**
It should upgrade itself.

**Screenshots**
The screenshot is in Italian, but you could easily guess what it is saying!

<img width="490" alt="Schermata 2019-06-04 alle 11 24 26" src="https://user-images.githubusercontent.com/20912806/58867787-5edc1a00-86bb-11e9-8aab-75460eb3ce25.png">

**Desktop (please complete the following information):**
 - macOS version: 10.14.5

**Additional context**
--

**Comment by aahung** [comment]
@domcorvasce thanks for reporting this. The change v0.5.5 does not bring any functional changes and I don't want to spam existing users (only 5 days after v0.5.4) so I made that release quiet.

**Comment by domcorvasce** [comment]
Ok, my bad then, sorry.

**Comment by aahung** [comment]
@domcorvasce oh no, please don't feel it that way, thanks for looking out for me. I should have labelled the release as "non-auto-update-release" (I just did it). :-D
