### ISSUE TITLE
Debug doesn't show anything.

### ISSUE THREAD

**Issue by anatoliliotych** [Aahung/Unshaky#9]
I'm trying to use the app, and it is just silent. There is no info in debug.

OS version: 10.13.6 (17G65)

**Comment by Aahung** [comment]
A key needs to be configured (with delay > 0) in order to show up in debug window.

**Comment by anatoliliotych** [comment]
So I'm seeing debug output, but it doesn't solve the problem? should I increase delay time?

**Comment by Aahung** [comment]
The delay I tested (according to my speed of typing) is 40ms, you may adjust a little bit. If it does not solve the problem, try with a higher value (like 100ms) to make sure it is working, then decrease gradually to fit your typing speed.

**Comment by anatoliliotych** [comment]
Many thanks! It fixed my issues with two keys :) You are my hero!

**Comment by Aahung** [comment]
So efficient, glad it works for you.
