### ISSUE TITLE
Disable touch bar when typing

### ISSUE THREAD

**Issue by gaohuia** [aahung/Unshaky#90]
**Problem**
I always touch the Touch Bar by accident when I was coding (fast typing).

**Solution**
Temporarily disable the TouchBar when typing, re-enable it when typing stops.

If no key was pressed for a period of time, we can consider the typing has stopped.

**Describe alternatives you've considered**
I just removed all the icons on TouchBar and press "fn" to show them.

**Comment by aahung** [comment]
@gaohuia I don't think it is some feature Unshaky should include. If you want to find a way to disable Touch Bar, this repo [TouchBarDisabler](https://github.com/Danesz/TouchBarDisabler) might help.
