### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by runar** [aahung/Unshaky#91]
**Language**
Norwegian (Bokmål)

**Can you help with the translation?**
Yes

**Comment by aahung** [comment]
Hi @runar thanks for your interest. A branch named "lang/nb" has been created and you can see 4 string files in "nb.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

Thanks!
