### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by bobodrone** [aahung/Unshaky#93]
**Language**
Swedish

**Can you help with the translation?**
Yes

**Comment by aahung** [comment]
Hi @bobodrone thanks for your interest. A branch named "lang/sv" has been created and you can see 5 string files in "sv.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!
