### ISSUE TITLE
Highlight menubar icon on shaky dismissal

### ISSUE THREAD

**Issue by Bradley-Walsh** [aahung/Unshaky#94]
Hi, I had one quick and (presumably) easily implementable addition to Unshaky I was wondering if you could add: Is there any way you could make the menubar icon highlight or light up when a shaky press is dismissed? It would be much easier to keep track of how often it happens while typing if so, rather than having to check by clicking the icon periodically. I’m only in the beginning stages of learning programming, but I’m relatively confident this would be no more than a simple addition. On a related note, thank you so much for making Unshaky. I work in transcription, and it’s been a huge help and time saver for me.

**Comment by aahung** [comment]
It is a cool suggestion, but from a user experience perspective, if every time a key is dismissed the icon blinks, it is distracting. The Unshaky is designed to make the problem disappear and user doesn’t have to worry about it.
