### ISSUE TITLE
Enable only for external keyboard

### ISSUE THREAD

**Issue by trevormeier** [aahung/Unshaky#97]
I have an external, foldable BT keyboard that's great for portability and raising my laptop with a stand, but occasionally it sends double keypresses inadvertently. I tried out Unshaky and it works great with this external keyboard! However, I have no issues (knock on wood) with my 2018 MBP keyboard, and Unshaky occasionally deletes intentional double keypresses when using it (I can type much faster on the MBP keyboard than on the BT keyboard).

Would it be possible to disable Unshaky for the built-in keyboard? As perhaps some variant of #14 ?

Thanks!

**Comment by trevormeier** [comment]
If this isn't straightforward, another possibility would be an assignable keyboard shortcut to quickly turn Unshaky on & off.

**Comment by niksawtschuk** [comment]
Ironically, I have the inverse issue of #14, i.e. my built-in keyboard works perfectly and my external USB keyboard frequently sends duplicated keypresses for a specific key.

So 👍 on this for me.

**Comment by aahung** [comment]
@niksawtschuk @trevormeier can you guys test the v0.6.0?

**Comment by niksawtschuk** [comment]
@aahung `Ignore Internal Keyboard` seems to work as intended in `v0.6.0`. Thanks!
