### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by alireza12t** [aahung/Unshaky#98]
**Language**
Persian/Farsi

**Can you help with the translation?** Yes
(Yes/No)

**Comment by aahung** [comment]
Hi @Alireza12s thanks for your interest. A branch named "lang/fa" has been created and you can see 5 string files in "fa.lproj"

For each file you will see several "some identifier here" = "some text in English here"; and only "some text in English here" part need translation. Besides, /* ... */ are comments and they don't need translation.

When you done, just create a PR.

Thanks!

**Comment by aahung** [comment]
Hi @Alireza12s just wanna check with you. Are you still gonna translate the last file [Localizable.strings](https://github.com/aahung/Unshaky/blob/lang/fa/Unshaky/fa.lproj/Localizable.strings)? Thanks!

**Comment by Alireza12s** [comment]
Yes it’s a bit harder i’ll do it

**Comment by pooya-alen1990** [comment]
I can help you to translate to Persian ;-)
