### ISSUE TITLE
Have Unshaky as a faceless app

### ISSUE THREAD

**Issue by ramyareye** [aahung/Unshaky#99]
Hey, thanks for your awesome package :) I'm writing well now. 
I'm happy to use your app but is it possible to have it in faceless mode ? I mean possible to remove the icon from top bar ?

Regards

**Comment by aahung** [comment]
Glad it works for you. 

See the article here for hiding task bar item

https://github.com/aahung/Unshaky/wiki/How-to-hide-Unshaky-from-status-bar
